// QACR-APP-EPIC-01 — epic and feature map.
//
// This file is the single source for the epic view. Milestones are NOT stated
// here: they are derived from the priority field of the requirements named in
// each feature, so the epic map cannot disagree with QACR-APP-FR-01.
//
// Feature row: [featureId, name, [FR ids], [BL ids], intent, uxNote]
//   FR ids  — in-scope requirements. Drive the derived milestone.
//   BL ids  — deferred items that belong to the same feature. Do not affect
//             the milestone; they carry their own backlog priorities.
//   intent  — what the feature is, in one or two sentences, for a reader who
//             has not read the requirements document.
//   uxNote  — the design artefact this feature needs, or the UX question it
//             raises. This is where user-experience work attaches.
//
// Epic: { code, title, summary, kind, features, journey, open }
//   kind    — "app" | "backend" | "content" | "process"
//   journey — where in the user journey the epic sits, or "cross-cutting"
//   open    — open register items (Q-nn) that block or reshape the epic

module.exports = [

{
  code: "E01",
  title: "App Foundation and Device Readiness",
  kind: "app",
  journey: "Before anything else — install, launch, and every entry into a test",
  summary: "Everything the application must establish before a test may begin: that the device is supported and uncompromised, that battery, storage, camera and connectivity are sufficient, and that the run-time configuration has been retrieved. The governing principle is that a failed check blocks the test rather than warning the user, so this epic owns the blocked-state pattern that some twenty other requirements refer to.",
  features: [
    ["F01.1", "Store distribution and install-time compatibility",
     ["FR-PLT-001", "FR-PLT-002", "FR-PLT-003", "FR-PLT-004"], [],
     "The application is published only to the Apple App Store and Google Play, with the stores' own hardware and OS filters set so that installation is prevented on unsupported models.",
     "No UI. Needs the store listing, screenshots and the supported-device statement.",
     [["M3", "Compatible with and installable on the supported iOS and Android versions, with the stores' own hardware and operating-system filters enabled so that an unsupported model cannot install."], ["M4", "Distribution restricted to the two application stores as the only channel."]]],
    ["F01.2", "Supported-device policy and run-time eligibility",
     ["FR-PLT-005", "FR-RDY-002", "FR-RDY-003", "FR-RDY-004"], [],
     "A backend-held list of supported operating-system versions and minimum hardware, checked at run time, plus a check of the application's own version against the backend. Any of the three failing prevents further use.",
     "Three blocking conditions with distinct copy: device unsupported, OS unsupported, update required. The version check is raised on a cold start and so is a full screen; the update case is the only one with an action the user can take, and it needs a route to the store."],
    ["F01.3", "Device integrity check",
     ["FR-RDY-001"], [],
     "Root detection on Android and jailbreak detection on iOS at start-up; a compromised device is blocked outright.",
     "One terminal blocking screen with no route forward. Decide whether support contact is offered here at all."],
    ["F01.4", "Pre-test resource and permission checks",
     ["FR-RDY-005", "FR-RDY-006", "FR-RDY-007", "FR-RDY-008", "FR-RDY-009", "FR-RDY-010"], [],
     "Internet connectivity, backend reachability, battery level, available storage and camera presence and permission, all re-evaluated immediately before a test starts and not only at launch.",
     "Settled at review: the checks run silently while the user is on the home screen, and surface on failure when the user taps start test. There is no visible checklist. Connectivity failures raised on a cold start are full screens; the rest are alerts. The camera permission is the exception to all of it — requested inside the instructional flow at the point the scan is reached, so the user understands why it is being asked.",
     [["M1", "The camera present and its permission granted, requested inside the flow at the point the scan is reached — the one check the demonstration needs, since the demonstration still has to scan."], ["M3", "Connectivity, backend reachability, battery level and available storage, all checked silently when the user taps start test, and re-run immediately before the test begins rather than only at launch."]]],
    ["F01.5", "Blocked-state pattern",
     ["FR-RDY-011", "FR-SUP-003", "FR-RDY-013", "FR-RDY-014"], [],
     "A single reusable presentation for every condition that blocks the user: what was detected, what to do about it, and how to reach support. Used by readiness failures, kit failures, timing failures, scan failures and backend errors alike.",
     "The highest-leverage component in the application. One template, parameterised. Two presentations, which is a user-interface decision rather than a requirement: conditions raised on a cold start are full screens, because an alert over the splash screen reads badly, and everything inside the flow is an alert. Content rules are FR-TXT-020; technical-detail suppression is FR-SEC-010. Support contact appears only where the user cannot resolve the condition themselves, and a retry only where retrying can succeed."],
    ["F01.6", "Deferred-upload recovery at start-up",
     ["FR-RDY-012"], [],
     "On launch the application determines whether data from an earlier test was transmitted and retries if not.",
     "Runs silently. Decide whether the user is told a previous result is still on its way, and what the home screen shows while that is true."],
    ["F01.7", "Cross-platform behavioural parity",
     ["FR-PLT-006"], [],
     "iOS and Android must present the same instructional content, step sequence, confirmation behaviour and error handling.",
     "A constraint on every screen in the application rather than a screen of its own. Worth stating in the design system."],
    ["F01.8", "Device and version telemetry on the test record",
     ["FR-PLT-008"], [],
     "Smartphone model, OS version and application version travel with the test record for image-validation and post-market analysis.",
     "No UI."],
    ["F01.9", "Run-time configuration",
     ["FR-CFG-001", "FR-CFG-002", "FR-CFG-008", "FR-LCM-018", "FR-CFG-003", "FR-CFG-004", "FR-CFG-006"], [],
     "The application retrieves its configuration from the backend before a test may start — every server-supplied value that governs its behaviour, of which the partner-specific ones are only a part — and refuses to fall back to values baked into the build if retrieval or schema validation fails.",
     "One blocking alert for configuration unavailable — the equivalent of the server-settings alert in the existing kidney application. The configured blocked state is now in scope at milestone 3, so it needs a defined response and a screen rather than being a gap.",
     [["M2", "Retrieval and schema validation of the configuration set before a test may start, with no fallback to an embedded set, and server-side enforcement of demonstration and mock result behaviour. Both moved here at the SPEC-04 review: the configuration set stops being demonstration-only at milestone 2, when it also carries a real test partner, and server-side enforcement cannot precede the channel that delivers it."],
      ["M3", "A defined response to a configured blocked state, and the configuration set in force recorded with the test."]]],
  ],
  open: ["Q-01 battery threshold", "Q-02 storage threshold", "Q-03 supported OS range", "Q-04 minimum hardware specification", "Q-32 configuration-set version not recorded with the test"],
},

{
  code: "E02",
  title: "Identity, Authentication and Consent",
  kind: "app",
  journey: "First launch, and again whenever the session has expired",
  summary: "Establishing that the person holding the phone is the patient the kit was dispatched to, because that association determines which record the result is written to and which provider it is routed to. Patient records already exist when the kit ships, so the application verifies a date of birth against a record rather than creating one. Consent is taken at the same moment.",
  features: [
    ["F02.1", "Phone number entry and lookup",
     ["FR-AUT-001", "FR-AUT-002", "FR-AUT-003", "FR-AUT-023"], [],
     "The user enters a phone number, the format is validated locally, and the backend reports whether it is already registered.",
     "Not the first screen: the onboarding sequence of F02.8 precedes it. Needs country-code handling, inline format validation and the consent checkbox from F02.7 on the same screen."],
    ["F02.2", "One-time password verification",
     ["FR-AUT-004", "FR-AUT-005", "FR-AUT-018", "FR-AUT-019", "FR-AUT-024"], [],
     "A six-digit code sent by SMS is submitted and validated server-side against an attempt count and an expiry, with a lockout when the limit is reached. The user can ask for the code again, or go back and correct the number.",
     "Code entry, a resend control that only becomes available after thirty seconds, a route back to phone entry, and a lockout state that says how long the wait is. Values are fixed: six digits, five minutes to expiry, five attempts, thirty seconds between resends, fifteen-minute lockout. Note that a resend spends an attempt, so the counter has to be visible enough that a user does not lock themselves out by pressing it.",
     [["M3", "The user submits the code delivered by SMS and it is verified."], ["M4", "The attempt limit, the five-minute expiry, the fifteen-minute lockout that follows five failures, and acceptance of a code the platform enters automatically."]]],
    ["F02.3", "Invite code for unregistered numbers",
     ["FR-AUT-006"], [],
     "A phone number not already registered must present an invite code, which the backend validates for authenticity and expiry.",
     "Follow the existing kidney application as a starting point."],
    ["F02.4", "Date-of-birth confirmation at test start",
     ["FR-AUT-008", "FR-AUT-010", "FR-AUT-012", "FR-AUT-020", "FR-AUT-007", "FR-AUT-011", "FR-AUT-015"], [],
     "The user confirms their date of birth at the start of every test, independently of login, and a mismatch blocks the test behind a deliberately generic error. The date of birth is not requested at login in this version.",
     "One screen at test start rather than a conditional login branch, since FR-AUT-009 is withdrawn. The behaviour ships behind a feature flag and is not shown to clinical-study participants; FR-FLW-006 is the requirement that provides that mechanism."],
    ["F02.5", "Session and token lifecycle",
     ["FR-AUT-013", "FR-AUT-014", "FR-SEC-008", "FR-COM-010", "FR-AUT-021", "FR-AUT-022"], [],
     "A token obtained on verification accompanies every request and expires after twenty-four hours. No credential is persisted on the device, and a retained token grants nothing after sign-out or expiry. The backend verifies the identity and authorisation carried by every incoming request and rejects any attempt to act on another patient's record.",
     "Design owes the re-verification experience: what the user sees when a token expires, and whether it can happen mid-journey. The 24-hour expiry taken from the backend SRS was flagged at review as wrong for this application and is open as Q-63."],
    ["F02.6", "Authentication guidance and failure support",
     ["FR-AUT-016"], [],
     "Each authentication step is guided, and repeated failure surfaces support contact information.",
     "Defines when the application stops retrying and starts helping. Uses the F01.5 pattern. Follow the existing kidney application as a starting point."],
    ["F02.8", "First-run onboarding",
     ["FR-AUT-017"], [],
     "Two or three screens on first launch, before authentication, introducing the application and the test, which the user may advance through or dismiss.",
     "Added at review. Sits ahead of F02.1 in the journey. Content is part of the versioned set and subject to the reading level, so it is drafted with E07 rather than separately."],
    ["F02.7", "Consent acknowledgement",
     ["FR-CNS-001", "FR-CNS-002", "FR-CNS-003", "FR-CNS-005", "FR-CNS-006", "FR-CNS-007"], [],
     "The Privacy Policy and Terms and Conditions are viewable from the verification screen and the main menu, and a mandatory checkbox on phone-number entry gates progress.",
     "Checkbox with inline links, presented without pre-selection. Recording which policy version was accepted is future development (FR-CNS-007, milestone 5), which design should know is not currently captured."],
  ],
  open: ["Q-21 does doctor-to-patient engagement happen in the application", "Q-23 whether the results center excludes results belonging to another user on the same phone number", "Q-63 the session-token expiry period is wrong as stated", "Q-65 which steps of the flow are conditional, and on what parameter"],
},

{
  code: "E03",
  title: "Kit Identification and Eligibility",
  kind: "app",
  journey: "At the scan, and at the moment a test is started",
  summary: "Ensuring only an authentic, unused kit produces a result. The design constraint that shapes this epic is that the kit identifier is printed on the Test Board and is therefore read during the scan, at the very end of the physical procedure — so reuse is detected rather than prevented, and the alert at test start is the only forward-looking control.",
  features: [
    ["F03.1", "QR capture and kit validation",
     ["FR-KIT-001", "FR-KIT-002", "FR-KIT-003", "FR-KIT-008", "FR-KIT-009"], [],
     "The QR code on the Test Board is located, read, validated against the identifier template and checked against the backend register of used kits. A code that cannot be read does not stop the scan — it is read during the scan, so the test completes and is refused afterwards where configuration says it should be. A refusal the software cannot attribute to a condition it recognises says nothing specific. Asking the user to present the code themselves is future development (FR-KIT-009, milestone 5). The same read and check run during a practice scan without registering the kit.",
     "Happens inside the scan screen, not as a separate step. The user has already run the assay by this point, so the failure copy must acknowledge that the kit is spent."],
    ["F03.2", "Reuse detection and new-kit gating",
     ["FR-KIT-004", "FR-KIT-007", "FR-KIT-005", "FR-KIT-010"], [],
     "A kit identifier already used invalidates the test at the point of scanning. Separately, starting a test within twenty-four hours of a previous one raises an alert requiring the user to confirm they hold a new kit.",
     "Reuse is detected, not prevented, because the identifier is only read at the scan. A practice scan reads it read-only, so practising on the kit under test cannot spend it. Two very different moments: a confirmation dialogue at the start, and a dead end at the end. The confirmation is presented with a message chosen by how the previous test ended, and the window excludes its endpoint. Expiry validation from the identifier is future development (FR-KIT-005, milestone 5), so an expired kit is not currently caught, and a backend refusal on a minimum interval between tests is future development too (FR-KIT-010)."],
  ],
  open: ["Q-15 the Risk Analysis says reuse is prevented; the application can only detect it at scan"],
},

{
  code: "E04",
  title: "Guided Test Flow Engine",
  kind: "app",
  journey: "The whole physical procedure, from sample collection to scan",
  summary: "The application is the sole means by which a lay user is guided through a multi-stage physical procedure, so the flow engine is the core of the product. Its interface is a chat-style exchange: one step at a time, the user confirms, the next arrives, and a spoken persona reads each bubble aloud. That explains a good deal of the rest of this document — why only the current instruction is visible, why the camera permission is requested inside the flow rather than before it,. This epic covers how the guidance is structured and how it survives interruption; what it must say is E07, and when it may advance is E05.",
  features: [
    ["F04.1", "Step sequencer and confirmation model",
     ["FR-FLW-001", "FR-FLW-004", "FR-FLW-005", "FR-FLW-006"], [],
     "The procedure is a sequence of short discrete steps in a fixed order, each requiring the user to confirm by activating a control, with only the current step's instruction visible and no route to a step not yet permitted. Steps may be included or omitted according to a parameter resolved outside the build.",
     "The single most important interaction pattern in the application, and it is a chat-style exchange rather than a paged wizard: one step at a time, the user confirms with a button, the next arrives. FR-FLW-006 makes steps conditional — the Date of Birth confirmation withheld from study participants is one example, the explanatory video after a result another. The full set of conditions and the chat behaviour they drive lives in the chat bubbles specification, not here.",
     [["M1", "The sequence itself: discrete ordered steps, a confirmation control on each, and only the current step's instruction visible."], ["M3", "Making steps conditional on a parameter resolved outside the build, which is how the date-of-birth step is withheld from clinical-study participants."]]],
    ["F04.2", "Instruction media, replay and spoken delivery",
     ["FR-FLW-002", "FR-FLW-003", "FR-FLW-008", "FR-FLW-010"], [],
     "Every step carries text and a video or animation of the action required, replayable while the step is active. The flow is also read aloud, and the user can silence it.",
     "Substantial production dependency: a video or animation per step, plus a spoken script for every bubble. Confirmed at review that not every demonstration is replayable — which are is defined per step, following the current usability application. The spoken delivery is a persona, a virtual nurse reading each bubble, with a mute control in the header; naming it is a content decision. Still needs a decision on autoplay and whether media is bundled or streamed, since a test may run on a poor connection."],
    ["F04.3", "State retention and interruption tolerance",
     ["FR-STA-002", "FR-STA-003", "FR-STA-005", "FR-STA-012"], [],
     "Test state, including all stage start times, is persisted. Calls, notifications and screen locks do not terminate the test; on return the user resumes at the active step with instructions replayable, and no inactivity timeout applies during a test.",
     "Mostly invisible when it works. Behaves as in the existing kidney application."],
    ["F04.4", "Termination detection and invalidation",
     ["FR-STA-006", "FR-STA-007"], [],
     "A test cannot be resumed after the application has been terminated by any cause, including a crash or a device restart. On reopening, the incomplete test is identified, invalidated, and the user told a new kit is needed.",
     "A harsh moment that a user may reach through no fault of their own, and the most likely source of support calls. Start from the existing kidney application and improve on it."],
    ["F04.7", "Scan practice",
     ["FR-IMG-022"], [],
     "During a timed waiting period the user can start a practice scan from the flow. It behaves like the real thing — the same QCR stage, the same boundary detection, the same guidance, and from milestone 3 the same QR validation — but has no scanning-window limit, ends with the waiting period, registers no kit and produces nothing.",
     "The point is that a user meets the scanning interaction while there is still time to struggle with it. Offered during the first timed stage, where the wait is longest. Design owes a clear distinction between practising and the real scan, so nobody believes they have already scanned."],
    ["F04.6", "Demonstration navigation",
     ["FR-FLW-007"], [],
     "In demonstration mode only, two controls: one advancing directly to a chosen section of the flow, one to the end of the section in progress. Both reachable by a deliberate gesture a user would not perform while taking a test, and both able to pass any timing window, since a demonstration produces no result for a patient.",
     "Added at review for milestone 1, and made two controls at the SPEC-04 review. The gesture is to be chosen — a sustained press on the start control or a device shake were both suggested. Demonstration mode is not a separate build: at milestone 1 it may be determined in the build, and from milestone 2 it comes from the configuration set like any other configured behaviour, on the same artefact that ships to patients. Pairs with F09.4."],
    ["F04.8", "Waiting-time card",
     ["FR-FLW-009"], [],
     "Where a timed wait is long enough, the flow opens a card showing the time remaining and content that changes as the wait elapses. The user does not choose whether it opens; the thresholds are fixed in the application. The content is optional, and the card yields whenever the flow needs the user to act.",
     "The requirement is the mechanism, not the content: a modal in the chat driven by elapsed time in the current stage, currently a sequence of tips. It is also where the countdown lives during a wait. Comes out of the reaction-phase research."],
    ["F04.5", "Cancellation",
     ["FR-STA-008", "FR-STA-009", "FR-STA-010"], [],
     "Cancellation is permitted only before the Urine Collection Cup has been filled. Requested after that, the user is warned the test cannot be resumed and a new kit will be needed, and must confirm.",
     "Two cancellation behaviours either side of one step. Where the exit affordance lives, and whether it disappears after cup fill, is a design decision."],
  ],
  open: ["Q-29 instructional comprehension has no stated verification activity", "Q-65 which steps of the flow are conditional", "Q-66 which gesture reveals the demonstration skip-to-step control"],
},

{
  code: "E05",
  title: "Assay Timing Control",
  kind: "app",
  journey: "Two windows inside the physical procedure",
  summary: "The assay is time-dependent at two stages: fluid held in the Incubation Wells until the user opens the Transfer Valve, and colour developing in the Detection Wells before the scan. The application is the only thing enforcing either window, which makes this epic safety-critical. Every value is fixed in the build and none is configurable.",
  features: [
    ["F05.1", "Timer framework and elapsed-time derivation",
     ["FR-TIM-001", "FR-TIM-002", "FR-TIM-003", "FR-TIM-004"], [],
     "Each timed stage has a start event, minimum duration, completion window and expiry behaviour. Start times are persisted and elapsed time is computed from them, so backgrounding or screen lock never restarts a timer.",
     "No UI, but everything in this epic rests on it. Note that elapsed time is currently derived from a source the user can alter; the hardened time source is future development (FR-TIM-004, milestone 5)."],
    ["F05.2", "Sample-freshness window",
     ["FR-TIM-006"], [],
     "Time from the user confirming sample collection to connecting the Sample Pod is measured, and exceeding the limit blocks progress.",
     "The first place the user can lose a kit to the clock. Settled at review: timed silently in the background with no countdown shown, so that the user is not hurried."],
    ["F05.3", "Incubation gate and release-button window",
     ["FR-TIM-007", "FR-TIM-009"], [],
     "The coloured release button instruction appears only once both the Incubation Well residence time has elapsed and the preceding instructions have been completed, and failing to operate the button within the permitted window invalidates the test.",
     "The critical interaction of the whole test. The user is waiting, then must act promptly. Design should treat the transition from waiting to acting as a distinct, unmissable event."],
    ["F05.4", "Colour-evolution gate and scanning window",
     ["FR-TIM-008", "FR-TIM-011"], [],
     "Progress past any timed stage before its minimum time is prevented, including scanning before colour evolution is complete, and the scan is permitted only inside the validated window.",
     "A second wait-then-act transition. Design should consider whether the two waits look the same to the user or deliberately different."],
    ["F05.5", "Timing display and expiry notification",
     ["FR-TIM-005", "FR-TIM-014", "FR-COM-009", "FR-COM-012"], [],
     "For each active timed stage the user sees the time until the next action is permitted and the time until the window expires. A local device notification fires when a window is about to expire, but only if the application is in the background.",
     "Two countdowns on one screen without alarming the user. Local notifications only; backend push is deferred, so the notification must not depend on connectivity. Permission is asked for behind an explainer of our own, so a refusal at the platform prompt is not the first thing the user sees — and refusing must not stop a test, since the on-screen countdown carries the obligation either way.",
     [["M1", "The on-screen display of time remaining until the next action is permitted and until the window expires."], ["M4", "The local device notification raised when a window is about to expire while the application is in the background, and the permission request that makes it possible."]]],
    ["F05.6", "Timing invalidation messaging",
     ["FR-TIM-012"], [],
     "A test invalidated on timing grounds tells the user why and instructs them to repeat with a new kit.",
     "Uses the F01.5 pattern. The reason must distinguish acted-too-early from acted-too-late."],
  ],
  open: ["Q-05 incubation, release-button, colour-evolution and scanning window values — nothing in this epic is verifiable until these exist", "Q-06 sample-collection to Sample Pod time limit", "Q-30 elapsed time can be derived from a source the user can alter"],
},

{
  code: "E06",
  title: "Scan Capture and Image Validation",
  kind: "app",
  journey: "The final action of the physical procedure",
  summary: "The Image Validation Transfer System is what makes a colorimetric measurement possible across a heterogeneous population of smartphone cameras. It works in two stages, and the distinction is the one thing worth carrying into a planning conversation: the QCR stage runs in real time while the user frames the board, and the algorithm pipeline runs on the captured set. Either can send the user back to scan again; only exhaustion of the scanning window invalidates the test. How each stage works is specified in the IVTS and algorithm documents rather than here. This is the largest single body of milestone-1 work.",
  features: [
    ["F06.1", "Camera acquisition and frame set",
     ["FR-CAM-001", "FR-CAM-002", "FR-CAM-003", "FR-CAM-004"], [],
     "Once the QCR stage accepts a frame, the remaining frames of the set defined by the IVTS specification are captured, including the torch state for each and any platform-specific frames. The specified camera adjustments are applied in response to a raised condition, the parameters used are recorded, and a camera failure mid-capture is recovered from.",
     "Little visible UI beyond the viewfinder, but the torch firing and the exposure shifting are visible to the user and should be explained rather than surprising.",
     [["M1", "Acquiring the IVTS frame set once the QCR stage has accepted a frame, with the specified torch state per frame, and recording the camera parameters that were applied."], ["M3", "Recovering when the camera becomes unavailable or returns an invalid frame mid-capture."], ["TBD", "The camera adjustments applied in response to a raised condition: white balance, exposure and tone mapping."]]],
    ["F06.2", "QCR stage",
     ["FR-IMG-001", "FR-IMG-002", "FR-IMG-010", "FR-IMG-011"], [],
     "The real-time stage, running while the user frames the board. A frame is accepted or rejected as it is seen, and acceptance is what triggers capture of the rest of the set.",
     "Settled at review: neither the scanning countdown nor a clock is shown, so that the user is not hurried. Design owes a way of conveying that another attempt is possible without implying time pressure. The gates are F06.3, the guidance F06.4; the detail is in the IVTS and algorithm specifications."],
    ["F06.3", "QCR gates",
     ["FR-IMG-004", "FR-IMG-005", "FR-IMG-006", "FR-IMG-007", "FR-IMG-008"], [],
     "The gates applied to each frame during the QCR stage. A gate failing rejects the frame and tells the user which condition to correct. The requirements here are the gates the Risk Analysis relies on; the full set is in the IVTS specification.",
     "Follow the existing kidney application design. Each gate needs a state the user can recognise and act on at a glance, while holding a phone over a board."],
    ["F06.6", "Algorithm pipeline and IVTS boundaries",
     ["FR-IMG-009", "FR-IMG-021", "FR-IMG-015", "FR-IMG-023"], [],
     "The captured set goes to the algorithm pipeline, which evaluates the IVTS boundary conditions. A boundary raises a message and the user may scan again; only exhaustion of the scanning window invalidates the test.",
     "Needs a state of its own while the pipeline runs, because the delay is long enough that a viewfinder with nothing happening reads as a failure. Specularity is the one boundary with no existing treatment to copy."],
    ["F06.4", "Real-time scan guidance, shown and spoken",
     ["FR-IMG-013", "FR-IMG-014", "FR-IMG-024"], [],
     "Guidance that runs during the QCR stage, steering the user towards a valid distance, angle and framing, and naming each condition that rejects a frame together with the correction. It is spoken as it changes, as well as shown.",
     "The user's eyes are on the board, not the screen, which is the whole reason for the spoken channel. Needs a voice script written for interruption and repetition, not just labels."],
    ["F06.5", "Colour normalisation",
     ["FR-IMG-016"], [],
     "Colours are normalised against the Color Print's standardised reference spectrum before colorimetric values are derived.",
     "No UI. Whether it happens on the device or in the backend is still open and affects where the work sits."],
  ],
  open: ["Q-09 IVTS acceptance thresholds and minimum valid frames", "Q-24 whether a raw or raw-equivalent representation is used, and where normalisation happens", "Q-67 the Risk Analysis trace for the specular-reflection boundary", "FR-CAM-002 priority undecided, and withdrawal is now an option"],
},

{
  code: "E07",
  title: "Instructional and Clinical Content",
  kind: "content",
  journey: "Cross-cutting — the words on every screen",
  summary: "What the application says, held separately from how it behaves so that instructional copy, warnings and result messaging can be drafted, read for comprehension and approved as one body of content. This is the epic with the largest dependency on people outside engineering, and the flow engine of E04 cannot be demonstrated without it.",
  features: [
    ["F07.1", "Content standards and control",
     ["FR-TXT-001", "FR-TXT-002", "FR-TXT-003", "FR-TXT-004", "FR-TXT-022", "FR-TXT-023"], [],
     "All user-facing text meets a Flesch-Kincaid grade-6 reading level, uses only the approved user-facing component names, does not contradict the User Manual, and is released as a versioned content set recorded with each test.",
     "Constrains every string in the product. The versioned content set implies content is not hardcoded, which is an architecture decision as much as a content one.",
     [["M2", "The grade-6 reading level and the approved component names, both of which the copy must meet before an intended user reads it unaided."], ["M3", "Consistency with the User Manual, release of the content as a versioned set whose version is recorded with each test, and text that scales with the device setting up to a defined maximum."],
      ["M4", "Screen-reader support on the content the software does not itself speak, without altering the conduct or the timing of a test."]]],
    ["F07.2", "Step instructional copy",
     ["FR-TXT-005", "FR-TXT-006", "FR-TXT-007", "FR-TXT-008", "FR-TXT-009", "FR-TXT-010", "FR-TXT-011", "FR-TXT-012", "FR-TXT-013", "FR-TXT-014", "FR-TXT-015", "FR-TXT-016", "FR-TXT-017"], [],
     "Thirteen requirements, one per physical action, in the order the user meets them: lighting, cup and lid, fill line, detaching the Sample Pod, seating it in the Mixing Cartridge, the Peel-Off Seal, flat surface, cartridge alignment, connection force, mixing, the coloured release button, shadow position, and disposal.",
     "Each pairs with a video or animation from F04.2. The Peel-Off Seal has no approved user-facing name yet, so its copy cannot be drafted."],
    ["F07.3", "Result and invalid-test copy",
     ["FR-TXT-019", "FR-TXT-021"], [],
     "The results screen carries the instruction not to act on the result without a professional, an explanation of what the measurement means, and the statement that it is shared with a clinician. Invalid-test messaging states the reason category and the corrective action.",
     "The most consequential copy in the product. Reading level and regulatory wording may conflict here.",
     [["M1", "The results-screen copy: what the measurement represents, what the category means, and not acting on it without a healthcare professional."], ["M3", "The invalid-test copy, which cannot be written until the reason enumeration in F08.4 exists."]]],
    ["F07.4", "Blocking and error message content",
     ["FR-TXT-020"], [],
     "Every message shown when the application blocks an action names the condition, states the corrective action and gives support contact, without disclosing sensitive information.",
     "The content half of the F01.5 pattern. One template plus a string set, roughly twenty-five instances across the product."],
  ],
  open: ["Q-18 no user-facing name for the Peel-Off Seal — instructional copy cannot be drafted without it", "Q-22 whether the grade-6 reading level applies to mandated regulatory wording", "Q-16 the Risk Analysis uses a component name the glossary does not define"],
},

{
  code: "E08",
  title: "Result Computation and Quality Control",
  kind: "backend",
  journey: "Between the scan and the result screen",
  summary: "Determining albumin, creatinine and the ratio from validated image data, and ensuring an invalid assay run never yields a reported number. Almost entirely backend and algorithm work, included here because the payload contract in F08.4 is what the application is built against, and because the invalidation reasons determine what the application can tell the user.",
  features: [
    ["F08.1", "Quantitation",
     ["FR-ALG-001"], [],
     "Albumin concentration, creatinine concentration and the ratio are determined from validated image data using an algorithm version approved for the applicable configuration.",
     "No UI. The application's dependency is timing: how long the user waits for this."],
    ["F08.2", "Algorithm version governance",
     ["FR-ALG-002", "FR-ALG-003", "FR-ALG-004"], [],
     "A controlled mapping between software configurations and approved algorithm versions, a check that the mobile and backend versions assigned to an exam are an approved combination, and a full record of versions, values and diagnostics per exam.",
     "No UI. Matters to the application only in that a mismatch must surface as an invalid test rather than a crash.",
     [["M2", "Recording the versions, values, raw results and diagnostics used for each exam."], ["M3", "The controlled mapping between supported configurations and approved algorithm versions."], ["TBD", "Enforcing that the mobile and backend versions assigned to an exam form an approved combination."]]],
    ["F08.3", "Assay quality control and invalidation",
     ["FR-ALG-005", "FR-ALG-006", "FR-ALG-007", "FR-ALG-008", "FR-ALG-009"], [],
     "Standard-curve quality control, recovery and blank well evaluation for interfering substances, detection of an incomplete assay run, detection that the sample never reached the buffer or that insufficient fluid reached the Detection Wells, and detection of insufficient colour output. Any failure blocks the result.",
     "No UI, but it generates most of the invalid-test outcomes the user will actually see. Note the capability limit: out-of-sequence assay signatures cannot be detected.",
     [["M2", "Detecting an incomplete assay run, and insufficient colour output in the standard curves."], ["M3", "Standard-curve quality control, and evaluation of the recovery and blank wells for interfering substances and discoloration."], ["TBD", "Detecting that the sample never reached the buffer, and that insufficient fluid reached the Detection Wells."]]],
    ["F08.4", "Result payload contract",
     ["FR-ALG-010", "FR-ALG-011", "FR-ALG-012"], [],
     "The payload distinguishes unambiguously between a valid quantitative result and an invalid test, conveys an out-of-range condition, and carries a reason category for every invalid test drawn from a defined enumeration.",
     "The interface the whole of E09 is built on. The enumeration should be agreed before the result screens are designed, because it sets how many distinct outcomes the user can be shown.",
     [["M2", "The unambiguous valid-or-invalid distinction, and the reason category carried for every invalid test."], ["M3", "Conveying that a result falls outside the claimed measuring range."]]],
  ],
  open: ["Q-27 RA 3.8 and RA 7.36 depend solely on FR-ALG-008, whose priority is undecided", "Q-40 whether FR-ALG-002 stays at milestone 3", "Q-64 whether the demonstration build needs real quantitation", "FR-ALG-003 and FR-ALG-008 priorities undecided"],
},

{
  code: "E09",
  title: "Result Presentation",
  kind: "app",
  journey: "Immediately after the scan and upload",
  summary: "What the user sees when a result comes back. Small in requirement count and large in consequence: this is the moment the product exists for, and the only moment at which a patient learns something about their kidney health.",
  features: [
    ["F09.1", "Result display",
     ["FR-RES-001", "FR-RES-002", "FR-RES-003", "FR-RES-007"], [],
     "The albumin-to-creatinine ratio is presented as both a number and a category, with units. The result shown is the one for the exam the application asked about, not simply the latest.",
     "Not a screen but a display: the same component is embedded in the chat at the end of the test and again in the results center, so it has to work in both places and at both sizes. Needs the categories, their boundaries and their visual treatment. Whether a raised result looks different from a normal one, and how much, is the central design question of this epic."],
    ["F09.2", "Out-of-range and invalid outcomes",
     ["FR-RES-004", "FR-RES-005", "FR-SUP-005"], [],
     "A result outside the claimed measuring range is presented as that condition rather than an unqualified number, and an invalid test shows no number at all.",
     "Three outcomes: valid, out of range, invalid. In the existing application the first two are screens and the third an alert, which is a user-interface decision rather than a requirement. However it is presented, the invalid outcome is reached by many different routes and should say which.",
     [["M1", "The invalid-test outcome, presented as an alert with no numeric value under any condition."], ["M2", "The out-of-range condition, presented as that condition rather than an unqualified number."],
      ["M3", "Asking, where a test is invalidated, whether the kit had already been spent on a practice or dry run."]]],
    ["F09.4", "Demonstration result",
     ["FR-RES-006"], [],
     "In a demonstration build the result comes from a fixed payload rather than an analysed test, is not presented as a clinical result, and the demonstration state is evident on every screen showing a result.",
     "Added at review so that milestone 1 can show a result before the payload contract exists. Demonstration mode is a backend flag rather than a separate build, so the marking is the only thing distinguishing a demonstration result from a real one — it has to be unmissable without dominating what is being demonstrated."],
  ],
  open: [],
},

{
  code: "E10",
  title: "Results Center, Main Menu and Support",
  kind: "app",
  journey: "After the test, and at any time outside a test",
  summary: "Everything the user reaches outside the test flow. The results center is a screen of its own holding previous results, protected by a PIN. The main menu, a hamburger on the home screen, is the route to the information an authenticated user may need at any time. Support contact belongs here too, since it is reachable both from the menu and from every blocked screen.",
  features: [
    ["F10.1", "PIN protection",
     ["FR-ACC-001", "FR-ACC-002", "FR-ACC-004", "FR-ACC-005", "FR-ACC-006", "FR-ACC-003", "FR-ACC-007", "FR-ACC-008"], [],
     "Access to the results center requires a four-digit numeric PIN, prompted for if not yet set. Five failed attempts deny access and direct the user to support. If no PIN is set within twenty-four hours of test completion, setup is locked and only support can reset it.",
     "A tight window with a hard edge. Prompting for the PIN inside the test flow, biometrics and support reset are all deferred, which means a user who does nothing for a day is locked out with no self-service route."],
    ["F10.2", "Results-center session control",
     ["FR-ACC-009"], [],
     "Fifteen minutes of inactivity in the results center returns the user to the home screen and requires the PIN to be entered again before re-entry.",
     "Applies to the results center only. An active test never times out, which is a deliberate asymmetry design should preserve."],
    ["F10.3", "Results center main screen",
     ["FR-PRT-001", "FR-PRT-007", "FR-PRT-009", "FR-PRT-010", "FR-PRT-011", "FR-PRT-014", "FR-PRT-015"], [],
     "A screen of its own showing the user's most recent result and the date that test was performed. Everything beyond that is deferred: the history of earlier results, viewing and sharing the results letter, and further information about the result.",
     "Separated at review. The results center main screen is milestone 3; the history screen of the last five results, reachable only where more than one result exists, is future development (FR-PRT-015). Two entry points: a dedicated control on the home screen, and the main menu. The results-letter and more-information entries pair with F11.4."],
    ["F10.4", "Main menu",
     ["FR-PRT-002", "FR-PRT-003", "FR-PRT-005", "FR-SUP-001"], [],
     "A hamburger menu on the home screen, available outside an active test, giving access to an About screen with the regulatory information, and to the Privacy Policy and Terms in a web view. A FAQ page is deferred.",
     "The menu's contents at milestone 3 determine its priority. Design should reserve room for the deferred entries rather than sizing it to what ships first.",
     [["M3", "The menu itself, reached from the hamburger on the home screen, and the About screen carrying the regulatory information."], ["M4", "The Privacy Policy and Terms and Conditions in an in-application web view."], ["Deferred", "The Frequently Asked Questions page."]]],
    ["F10.5", "Support contact",
     ["FR-SUP-002", "FR-PRT-004", "FR-SUP-004"], [],
     "Telephone and email support, reachable from the main menu without starting a test as well as from every blocked screen. In-application support chat is deferred.",
     "The escape hatch for the whole product. Consider what context is carried into the call or email, since the user will not know their test identifier. Support contact is not shown on every blocking alert — only where the user cannot resolve the condition themselves."],
    ["F10.6", "Post-test lobby",
     ["FR-PRT-012", "FR-PRT-013"], [],
     "The home screen becomes a post-test lobby after a successful test, presenting the actions defined for the result type and instrumented accordingly. Deferred in full.",
     "Deferred, but it is the home screen, so its absence is itself a design question: what does the home screen show for the ninety days after a test in this version?"],
  ],
  open: ["Q-23 what the results center contains", "Q-28 a user who forgets their PIN has no recovery path, since FR-ACC-003, FR-ACC-007 and FR-ACC-008 are all future development", "Q-39 whether the results center can be delivered in time for milestone 3"],
},

{
  code: "E11",
  title: "Result Routing and Sharing",
  kind: "backend",
  journey: "After the result, mostly invisible to the user",
  summary: "Getting the result to the right clinician, recorded against the right patient. In this version it travels through the backend and the user does nothing; every user-initiated sharing route is deferred. The application-side consequence is that the result screen has no share action in this release.",
  features: [
    ["F11.1", "Tenancy and patient mapping",
     ["FR-SHR-001", "FR-SHR-002", "FR-SHR-003", "FR-SHR-004"], [],
     "The data model is segmented by partnering organisation with logical isolation between providers, each patient maps to one provider organisation, each result maps to the patient record behind the verified token, and each provider has its own integration configuration.",
     "No UI. This is the control that prevents a result reaching the wrong patient or the wrong provider. Follow the existing kidney application: either the prescription comes from our third-party prescriber, or the partner organisation provides it."],
    ["F11.2", "Provider integration and delivery",
     ["FR-SHR-005", "FR-SHR-006", "FR-SHR-007", "FR-SHR-008", "FR-SHR-017"], [],
     "HL7-based integration with a documented per-provider mapping, handshake and acknowledgement, retry on failure, rejection of malformed transmissions and access denied to unauthorised addresses. HISP delivery to primary care providers was separated at review and is deferred.",
     "No UI. Worth knowing that delivery failure is invisible to the user, who is told the result was shared. The prescribing model is as F11.1."],
    ["F11.3", "Post-result journey per partner",
     ["FR-SHR-011"], [],
     "Configuration states, per partner, whether doctor-to-patient engagement happens inside the application or outside it, and the application presents the corresponding post-result journey.",
     "This one requirement decides whether an entire branch of the product exists for a given partner. Priority undecided."],
    ["F11.4", "User-initiated sharing",
     ["FR-SHR-012", "FR-PRT-008", "FR-SHR-015", "FR-SHR-016", "FR-SHR-018"], [],
     "Sharing the result with a primary care provider, generating a results letter as a PDF, opening a configured web page, and handing off to an external application where a sharing action requires one. All deferred.",
     "Deferred. The hand-off is guarded: only explicitly configured applications, only user-initiated, only the minimum data the action needs. The option set varies with what is installed — FR-SHR-018, future development, checks for a configured sharing application and presents the options that apply. Note the unresolved tension with FR-SEC-007, which prevents screenshots of result screens while one of these options saves the results letter to the photo library; see Q-81."],
    ["F11.5", "Doctor engagement and post-test consultation",
     ["FR-SHR-013", "FR-SHR-014"], [],
     "A chat with a doctor before or after a test, and calling a primary care provider or care team on a configured number. Deferred, and conditional on F11.3.",
     "Do not design the post-result screens as though this exists until the partner question in F11.3 is settled. It is the branch that decides whether the product ends at the result or continues into a consultation."],
    ["F11.6", "Post-test feedback survey",
     ["FR-ANL-006", "FR-ANL-007", "FR-ANL-008"], [],
     "A configured survey opened in an in-application web view, declinable, and unable to block or delay the result. Deferred.",
     "Moved out of the result-presentation epic at review: the survey belongs after the consultation rather than immediately after the result, because by then the user has already seen the result. It follows F11.5 and so inherits its dependency on the partner question."],
    ["F11.7", "Application rating prompt",
     ["FR-ANL-009"], [],
     "The operating system's own application-store rating prompt, presented at the end of the consultation flow. Deferred.",
     "Separate from the survey because it is the platform's prompt rather than ours, and it is asked once in the lifetime of an install rather than after every test. Timing matters: it should not follow an invalid test or a raised result."],
  ],
  open: ["Q-21 does doctor-to-patient engagement take place within the application", "Q-81 screenshot prevention against saving the results letter to the photo library", "FR-SHR-011 priority undecided"],
},

{
  code: "E12",
  title: "Connectivity and Data Transmission",
  kind: "app",
  journey: "At the scan, and in the background afterwards",
  summary: "Moving the captured data to the backend and surviving the fact that a home user's connection is unreliable at exactly the wrong moment. The transport requirements also carry most of the threat-analysis controls for data in transit.",
  features: [
    ["F12.1", "Secure transport",
     ["FR-COM-001", "FR-COM-002", "FR-SEC-014"], [],
     "HTTPS over TLS 1.2 or above with strong cipher suites, chain verification and strong session identifiers, refusing anything negotiated lower, and certificate pinning so only the expected certificate is accepted. Until both are implemented, no build may carry personal or health information.",
     "No UI. A pinning failure needs a user-facing outcome, which today falls to the generic blocked-state pattern. FR-SEC-014 was added at review to keep patient data out of the milestone-1 build.",
     [["M1", "The constraint that no build in which the transport controls are unimplemented may carry personal or health information — which is what makes the demonstration build acceptable."], ["M3", "TLS 1.2 or above with strong cipher suites and chain verification, and certificate pinning."]]],
    ["F12.2", "Upload, retrieval and integrity",
     ["FR-COM-003", "FR-COM-004", "FR-COM-005", "FR-COM-007", "FR-COM-011", "FR-SEC-006"], [],
     "Captured data is transmitted with an integrity check and an upload indication; the backend treats everything received as untrusted and rejects malformed payloads; the application then requests the result and shows a waiting state until one arrives; on acknowledgement the user may conclude the test and local test data is deleted.",
     "FR-COM-011 was added at review and closes UX-02: the waiting state between upload and result is now a requirement rather than a gap. The period after which the user is told how the result will reach them is still unvalued.",
     [["M1", "Transmitting the captured data with an integrity check, the backend rejecting malformed payloads, then requesting the result and holding a waiting state until one arrives."], ["M3", "Concluding the test on backend acknowledgement and deleting the local test data."]]],
    ["F12.3", "Interrupted upload and retry",
     ["FR-COM-006", "FR-COM-008"], [],
     "Losing connectivity mid-upload notifies the user, retains the data, retries automatically and resumes when connectivity returns. A backend error is explained with the next steps available.",
     "The user may walk away mid-upload. Design owes the state they come back to, and how they learn a result arrived later.",
     [["M1", "Explaining a backend error and the next steps available to the user."], ["M3", "Retaining the data on connectivity loss, retrying automatically, and resuming when connectivity returns."]]],
    ["F12.4", "Push notifications",
     ["FR-COM-013"], [],
     "Receipt of push notifications from the backend. Deferred, which is why the timing notification in F05.5 is local only.",
     "Deferred. Nothing may be designed to depend on a server-initiated message."],
  ],
  open: [],
},

{
  code: "E13",
  title: "Security and Privacy",
  kind: "app",
  journey: "Cross-cutting",
  summary: "Protecting personal and health information on the device and in transit. Almost all of it originates in the Security and Privacy Threat Analysis, which remains the authority for the threat model; these are the application obligations that follow from it. Little of it is visible to the user, with one prominent exception in F13.3.",
  features: [
    ["F13.1", "Data at rest and minimisation",
     ["FR-SEC-001", "FR-SEC-009"], [],
     "Sensitive data stored on the device is encrypted and limited to what completing the test requires, and cryptographic keys and session tokens live only in the iOS Keychain or Android Keystore.",
     "No UI."],
    ["F13.2", "Build hardening",
     ["FR-SEC-002", "FR-SEC-003", "FR-SEC-012"], [],
     "Code obfuscation on Android, all debugging functionality disabled in release builds, and encrypted release artefacts on both platforms.",
     "No UI. Build and release pipeline work rather than feature work."],
    ["F13.3", "Screen and preview protection",
     ["FR-SEC-007"], [],
     "Screenshots of any screen carrying personal, health or result information are prevented, and such content is obscured when the application is backgrounded so it does not appear in the app switcher.",
     "The one security requirement the user will notice, and they will notice it at the worst moment: trying to screenshot their own result to send to someone. Worth an explicit design response."],
    ["F13.4", "Error hygiene and input validation",
     ["FR-SEC-004", "FR-SEC-005", "FR-SEC-010", "FR-SEC-011"], [],
     "Error messages disclose neither personal information nor internal technical detail; logs and crash reports carry no personal or health information; and all user-supplied input is validated and sanitised against the expected type, length and character set.",
     "Sets a floor under the copy in F07.4: no stack traces, endpoints or component versions in anything the user can see."],
    ["F13.5", "Security audit events",
     ["FR-SEC-013"], [],
     "Security-relevant events are reported to the backend for audit logging, including authentication attempts, PIN failures, integrity-check failures and blocked test starts, carrying no personal or health information.",
     "No UI. A separate channel from analytics, though the same privacy constraint applies to both."],
  ],
  open: [],
},

{
  code: "E14",
  title: "Analytics",
  kind: "app",
  journey: "Cross-cutting",
  summary: "Instrumentation for observing how the application is actually used in the field, subject to the constraint that it may carry no personal or health information and may never become a dependency of the clinical flow.",
  features: [
    ["F14.1", "Event instrumentation",
     ["FR-ANL-001"], [],
     "Events for progress through the test flow: step entry and completion, blocking conditions raised, scan attempts and their outcomes, and test completion or invalidation.",
     "Mixpanel. The event taxonomy should be designed alongside the flow rather than retrofitted, since the step boundaries are the events."],
    ["F14.2", "Analytics privacy constraints",
     ["FR-ANL-002", "FR-ANL-003"], [],
     "No personal information, health information or result values in any event, and events tied to a pseudonymous identifier the analytics provider cannot resolve to a patient.",
     "No UI. Constrains what any dashboard can ever show, which is worth saying out loud before dashboards are specified."],
    ["F14.3", "Analytics resilience",
     ["FR-ANL-005"], [],
     "Failure or unavailability of the analytics service must not prevent a test being started, completed or reported.",
     "No UI."],
    ["F14.4", "Proxy routing",
     ["FR-ANL-004"], [],
     "Routing events through the configured proxy endpoint rather than directly to the provider. Deferred.",
     "Deferred, so events reach the provider directly for now; the exposure is limited to event metadata by F14.2."],
  ],
  open: ["Q-34 analytics events will reach the provider directly rather than through the proxy"],
},

{
  code: "E15",
  title: "Verification and Release Process",
  kind: "process",
  journey: "Not user-facing",
  summary: "Risk controls implemented through how the software is built, tested and released rather than through anything the application does. Not feature work, and not a backlog either — each item is relied upon by the Risk Analysis and needs an owner. Development standards including unit testing sit in the Software Development Plan, not here.",
  features: [
    ["F15.1", "System parameter control",
     ["FR-LCM-006"], [],
     "Every system parameter has a value, permitted range and documented rationale before design verification, held under configuration control whether fixed in the build or supplied by configuration.",
     "This is the gate the open parameter values in the register must pass through."],
    ["F15.2", "Timing and state verification",
     ["FR-LCM-007", "FR-LCM-008", "FR-LCM-011"], [],
     "Each timer and timing window verified separately including under backgrounding and interruption; regression testing of the timing and state controls each release; and verification of state retention, termination and reopening at every stage of the flow.",
     "The verification counterpart to E04 and E05. Test design should start when those epics do, not after.",
     [["M3", "Verifying each timer and window separately including under backgrounding and interruption, and verifying state retention, termination and reopening at every stage of the flow."], ["M4", "Regression testing the timing and test-state controls at each applicable release."]]],
    ["F15.3", "Algorithm and release verification",
     ["FR-LCM-009", "FR-LCM-010", "FR-LCM-017"], [],
     "Verification and validation of each algorithm version and approved version combination, with regression against a validated reference algorithm where a full analytical study is not repeated; confirmation that approved versions and configuration reached production; and release testing before each release.",
     "Counterpart to E08."],
    ["F15.4", "Off-the-shelf component management",
     ["FR-LCM-002", "FR-LCM-003", "FR-LCM-004", "FR-LCM-005"], [],
     "Third-party components evaluated before integration and obtained only from official sources, validated within the whole system before release, inventoried continuously by a scanning tool, and monitored for vulnerabilities and supplier notifications with changes assessed through change control.",
     "Tooling and subscription decisions, including the vulnerability bulletins the threat analysis names."],
    ["F15.5", "Usability testing",
     ["FR-LCM-012"], [],
     "Usability testing includes representatives of each supported platform and evaluates foreseeable interruptions before, during and after result-critical actions.",
     "The milestone-2 usability rehearsal is where this begins. Note that comprehension of the instructions has no stated verification activity here and is assumed to sit in the Usability Engineering Plan."],
    ["F15.6", "Provider integration testing",
     ["FR-LCM-016"], [],
     "A dedicated integration testing phase with each medical provider before go-live, covering connectivity, transmission and mapping accuracy, routing and the handling of failures.",
     "Per provider organisation, so it repeats for each partner."],
  ],
  open: ["Q-29 instructional comprehension has no stated verification activity in this document"],
},

];
