// Identifier stability guard.
//
// Answers the question raised at the Rev 1.7 review: can identifiers actually be
// kept stable, or is that only a promise? This makes it a mechanism.
//
// Every identifier ever issued is recorded in id-manifest.json. On each build the
// guard checks that each one is still accounted for in one of the four places an
// identifier may legitimately live:
//
//   in scope          — a row in the requirement tables
//   withdrawn         — a row in Appendix D
//   deferred          — an entry in Appendix E
//   superseded        — named in a "formerly FR-..." note on a deferred entry
//   promoted          — a deferred item brought into scope, named "formerly BL-nn"
//                       by the requirement that absorbed it
//
// An identifier that disappears from all four fails the build. A new identifier is
// added to the manifest automatically, so the manifest grows but never shrinks, and
// a number is never reissued because the guard would see it as already recorded
// against a different disposition.

const fs = require("fs");
const path = require("path");

function collect(sections, APX) {
  const where = new Map();
  sections.forEach(s => s.reqs.forEach(r => {
    where.set(r[0], "in scope");
    // A deferred item can also be promoted into scope, in which case the
    // requirement that absorbed it names it and the BL identifier stays retired.
    const m = (r[2] + " " + r[3]).match(/formerly (BL-\d{2})/g) || [];
    m.forEach(x => {
      const id = x.replace("formerly ", "");
      if (!where.has(id)) where.set(id, "promoted into scope as " + r[0]);
    });
    // A requirement may also carry the identifier it held two steps back. The four
    // survey requirements were FR-SUR-001 to 004, superseded to BL-29 to BL-32, and now
    // sit in FR-ANL. When the backlog was emptied at Rev 1.18 the middle link vanished,
    // so without this the FR-SUR identifiers were accounted for nowhere — which is how
    // this guard reported it.
    const o = (r[2] + " " + r[3]).match(/[Oo]riginally (FR-[A-Z]{3}-\d{3})/g) || [];
    o.forEach(x => {
      const id = x.replace(/[Oo]riginally /, "");
      if (!where.has(id)) where.set(id, "superseded, now " + r[0]);
    });
  }));
  APX.withdrawn.forEach(r => {
    const id = r[0].replace(/ \(earlier wording\)$/, "");
    if (!where.has(id)) where.set(id, "withdrawn");
  });
  APX.backlog.forEach(r => {
    where.set(r[0], "deferred");
    const m = (r[2] + " " + r[3]).match(/formerly (FR-[A-Z]{3}-\d{3})/g) || [];
    m.forEach(x => {
      const id = x.replace("formerly ", "");
      if (!where.has(id)) where.set(id, "superseded, now " + r[0]);
    });
  });
  return where;
}

// Identifiers that were issued at some point but carry no text anywhere. Recorded
// so that the gap is deliberate rather than silent; see the review register.
const UNACCOUNTED = ["FR-IMG-018", "FR-IMG-019", "FR-SHR-009", "FR-SHR-010", "FR-TIM-013"];

module.exports = function guard(dir, sections, APX, opts = {}) {
  const file = path.join(dir, "id-manifest.json");
  const now = collect(sections, APX);
  UNACCOUNTED.forEach(id => now.set(id, "unaccounted — see the review register"));

  let manifest = { issued: {}, note: "Generated by id-guard.js. Never edit by hand; never delete an entry." };
  if (fs.existsSync(file)) manifest = JSON.parse(fs.readFileSync(file, "utf8"));

  const vanished = [];
  const reissued = [];
  for (const id of Object.keys(manifest.issued)) {
    if (!now.has(id)) vanished.push(id + " (was " + manifest.issued[id] + ")");
  }
  const added = [];
  for (const [id, disp] of now) {
    if (!(id in manifest.issued)) { added.push(id + " (" + disp + ")"); manifest.issued[id] = disp; }
    else if (manifest.issued[id] !== disp) {
      // A change of disposition is legitimate — in scope to withdrawn, for example.
      // A number moving from withdrawn back to in scope is a reissue, which is not.
      if (manifest.issued[id] === "withdrawn" && disp === "in scope") reissued.push(id);
      manifest.issued[id] = disp;
    }
  }

  if (vanished.length || reissued.length) {
    console.error("identifier guard failed:");
    vanished.forEach(v => console.error("  vanished, accounted for nowhere: " + v));
    reissued.forEach(v => console.error("  reissued after withdrawal: " + v));
    process.exit(1);
  }

  fs.writeFileSync(file, JSON.stringify(manifest, null, 1) + "\n");
  if (opts.verbose) {
    console.log("identifier guard: " + Object.keys(manifest.issued).length + " identifiers on record"
      + (added.length ? ", " + added.length + " newly issued: " + added.join(", ") : ""));
  }
  return manifest;
};
