// QACR Mobile App - Functional Requirements data (part 1 of 2) - Rev 0.5
// Row format: [id, requirement, source, notes, priority]
// Priority is the FDA-submission implementation priority: 0 Must, 1 High,
// 2 Medium, 3 Low. "TBD" where the review left it undecided.
// Identifiers are now stable. Withdrawn identifiers are not reissued.

module.exports = [

{
  code: "4",
  title: "Platform, Distribution and Compatibility",
  intro: "Requirements governing which smartphones and operating systems the application supports, and how compatibility is enforced before the application can be used.",
  reqs: [
    ["FR-PLT-001", "The software shall be distributed exclusively through the Apple App Store and Google Play Store.", "RA 4.15", "", "4"],
    ["FR-PLT-002", "The software shall be compatible with, and installable on, Apple iOS from the minimum version established by the IVTS device qualification.", "SRS LOC.1", "Minimum version TBD, to follow from the IVTS device qualification. iosMinOsVersion currently 13.0.0", "3"],
    ["FR-PLT-003", "The software shall be compatible with, and installable on, Android OS from the minimum version established by the IVTS device qualification.", "SRS LOC.2", "Minimum version TBD, to follow from the IVTS device qualification. androidMinOsVersion currently 8.0.0", "3"],
    ["FR-PLT-004", "The software shall be published to the application stores with hardware and operating-system compatibility filters enabled, so that installation is prevented on device models that are not supported.", "RA 4.5", "", "3"],
    ["FR-PLT-005", "The software shall maintain a backend-configurable list of supported operating-system versions and minimum hardware characteristics.", "RA 4.5, 4.8", "Narrowed per review: the Risk Analysis calls for hardware characteristics and operating systems, not a list of unsupported phone models. Model-level exclusion remains available through the store compatibility filters in FR-PLT-004", "3"],
    ["FR-PLT-006", "The iOS and Android implementations shall present functionally equivalent instructional content, step sequence, confirmation behaviour and error handling, so that the user experience is consistent across supported platforms.", "RA 4.7", "", "2"],
    ["FR-PLT-008", "The software shall record the smartphone model, operating-system version and application version in the test record transmitted to the backend.", "RA 4.7, 4.8, 4.22", "Required for IVTS and post-market analysis", "3"],
  ]
},

{
  code: "5",
  title: "Pre-Test Readiness Verification",
  intro: "Checks the software performs at application start-up and again immediately before a test is initiated. A failed readiness check prevents the test from starting; it does not produce a warning that the user may dismiss.",
  reqs: [
    ["FR-RDY-001", "Upon start-up, the software shall verify device integrity (root detection on Android, jailbreak detection on iOS). If a compromised device is detected, the software shall block access and prevent further use.", "SRS STM.1; SPTA 4.11", "", "3"],
    ["FR-RDY-002", "Prior to test initiation, the software shall programmatically verify that the smartphone hardware characteristics meet the defined minimum technical specifications. The user shall not be permitted to start a test if the requirements are not met.", "RA 4.5", "Specification derived from the analytical studies. Realised by staticData.supportedHardwareConfig", "3"],
    ["FR-RDY-003", "The software shall verify that the operating-system version is within the supported range. If the version is outside that range, the software shall prevent further use and display an explanatory message.", "RA 4.6; SPTA 2.5; SRS STM.4, STM.5; SRS-BE COM.2", "Range TBD. The lower bound is constrained twice: by the IVTS device qualification, and by SPTA 2.5, which requires that versions no longer receiving security updates cannot be used to take a test. The binding constraint is whichever is higher. Also validated server-side per SRS-BE COM.2", "3"],
    ["FR-RDY-004", "The software shall verify its own version against the backend. If the application version is unsupported, the software shall prevent further use and shall direct the user to the application's listing in the store from which it was installed. Whether an available update is mandatory or may be dismissed shall be determined by configuration.", "RA 4.17; SRS STM.4, STM.5; SRS-BE COM.2, COM.4", "The backend independently validates device type, operating-system version and application version on the settings request and returns a failure response, so the check is enforced on both sides. Realised by iosMinAppVersion, androidMinAppVersion, forceUpdateOnPreLogin", "3"],
    ["FR-RDY-005", "The software shall verify that the smartphone has an active internet connection. If no connection is available, the software shall prevent the test from starting and display an explanatory message.", "RA 5.2", "", "3"],
    ["FR-RDY-006", "The software shall verify that the backend server is reachable. If the backend cannot be reached, the software shall prevent the test from starting and display an explanatory message.", "RA 5.3; SRS STM.2", "", "3"],
    ["FR-RDY-007", "The software shall verify that the battery level is at or above the defined minimum threshold. If the battery level is below the threshold, the software shall prevent the test from starting and instruct the user to charge the device.", "RA 4.13; SRS STM.3", "Threshold TBD; fixed in the application, not configurable", "3"],
    ["FR-RDY-008", "The software shall verify that available storage is at or above the defined minimum threshold. If storage is insufficient, the software shall prevent the test from starting and instruct the user to free storage.", "RA 4.14; SRS STM.6, STM.7", "Threshold TBD, and fixed in the application rather than configuration-supplied. Unlinked from staticData.lowDiskSpaceSize at review", "3"],
    ["FR-RDY-009", "The software shall verify that the camera is present, and shall request camera permission at the point in the instructional flow where it is required. If the camera is absent, if permission is not granted, or if the camera cannot be started, the software shall not permit the user to proceed.", "RA 4.9", "Restated at review. Unlike the other checks in this section, the camera permission is requested inside the instructional flow at the point of need rather than silently before the test starts, so the user understands why it is being asked. Refusal blocks progress rather than warning", "1"],
    ["FR-RDY-010", "The software shall re-evaluate all readiness checks immediately before test initiation, and not only at application start-up.", "RA 4.5, 4.13, 4.14", "", "3"],
    ["FR-RDY-011", "When a readiness check fails, the software shall present a single message that identifies the condition and states the corrective action required, together with support contact information. Each condition shall be defined as either preventing the test from starting, or informing the user and permitting them to continue.", "RA 4.15, 4.16", "Content per FR-TXT-020", "3"],
    ["FR-RDY-013", "Where a condition that blocks the user can be resolved by attempting the action again, the software shall offer the user a means of retrying it. Where the condition cannot be resolved by retrying, the software shall not offer a retry, and shall present only the route to resolution that applies.", "Review comment; extends RA 4.15, 4.16", "Added at review. The distinction matters because a retry offered on an unrecoverable condition invites the user to repeat an action that cannot succeed. Whether a given condition is retryable is to be stated for each blocking condition in this document before design verification", "3"],
    ["FR-RDY-014", "Where the backend refuses to permit a test, the software shall present a message specific to the reason given, identifying the condition and the action available to the user.", "Review comment; QACR-APP-SPEC-01", "Added at review. The backend answers the start-up exchange with at most one reason why this user may not test, and each reason needs its own message rather than a generic failure. The reasons themselves are the backend contract and are not enumerated here; Appendix I records the set the current product raises. Complements FR-CFG-006, which requires a reason to be given without saying what the reasons are", "3"],
    ["FR-RDY-012", "Upon start-up, the software shall determine whether previously collected test data was successfully transmitted to the backend and, if not, shall attempt to retransmit it.", "SRS STM.8; RA 5.2, 5.3", "RA trace added per review", "3"],
  ]
},

{
  code: "6",
  title: "User Onboarding, Identification and Authentication",
  intro: "Requirements ensuring that the person performing the test is reliably associated with the correct patient record, since that association determines to which record the result is written and to which provider it is routed. Patient records are created before the kit is dispatched and are not created by the application, so the Date of Birth is verified against an existing record rather than collected.",
  reqs: [
    ["FR-AUT-001", "The software shall enable the user to initiate the authentication process by entering a phone number.", "SRS AUT.1", "", "3"],
    ["FR-AUT-002", "The software shall validate the phone-number format and prevent the entry of invalid or special characters.", "SRS AUT.2", "", "3"],
    ["FR-AUT-003", "The software shall transmit the phone number to the backend to determine whether it is already registered in the system. Where the backend does not respond, the software shall not present the number as unregistered.", "SRS AUT.3", "Realised by allowCreation (false for this app)", "3"],
    ["FR-AUT-004", "The software shall complete one-time password (OTP) verification by enabling the user to submit a six-digit OTP delivered by SMS from the backend.", "SRS AUT.4; RA 4.16", "Length is six digits, taken from the existing kidney application; confirm before design verification", "3"],
    ["FR-AUT-018", "The software shall enable the user to request that the one-time password be sent again. Each such request shall count against the attempt limit of FR-AUT-005, and the software shall require a defined interval to elapse before a further request can be made.", "Review comment; SRS AUT.5", "Added at review. The interval is 30 seconds. Resending counts against the attempt limit, so the limit governs requests and submissions together", "3"],
    ["FR-AUT-019", "While awaiting a one-time password, the software shall enable the user to return to phone-number entry in order to correct the number, and shall discard the pending verification when they do.", "Review comment", "Added at review, for the case where the user mistyped the number", "3"],
    ["FR-AUT-005", "The software shall validate the submitted OTP against the defined attempt-count and expiration limits. Where the attempt limit is reached, the phone verification process shall be locked for the defined lockout period.", "SRS AUT.5; SRS-BE AUT.4, AUT.5, AUT.6", "Values set by the backend SRS: OTP expires after 5 minutes, and 5 consecutive failures lock verification for 15 minutes. Enforced server-side. Resolves the parameter formerly open as O-04", "4"],
    ["FR-AUT-006", "If the phone number is not registered, the software shall require the user to enter an invite code, which the backend shall validate for both authenticity and expiry.", "SRS AUT.6; SRS-BE AUT.10, AUT.11, AUT.12", "Expiry validation added from the backend SRS. Realised by allowRegistration (true)", "4"],
    ["FR-AUT-008", "The software shall validate that the entered Date of Birth meets the required format.", "SRS AUT.8", "Applies to the Date of Birth confirmed at the start of a test per FR-AUT-012, not to login. Milestone follows FR-AUT-012", "3"],
    ["FR-AUT-010", "If the Date of Birth confirmed at the start of a test is mismatched or invalid, the software shall prevent the user from proceeding and shall present a generic error that does not disclose which element of the identification was at fault.", "SRS AUT.10; SRS-BE AUT.15; RA 6.4; SPTA 1.3", "Restated at review: the Date of Birth is no longer requested at login, so this governs the confirmation required by FR-AUT-012. Everything required for the submission is required for the clinical study, so milestone 3, held behind a feature flag so that the behaviour is present and verifiable without being shown to study participants. The error is generic, per the backend SRS and SPTA 1.3", "3"],
    ["FR-AUT-012", "The software shall require the user to confirm their Date of Birth at the start of every test, independently of the login flow and irrespective of how many users are registered against the phone number.", "RA 6.4", "Everything required for the submission is required for the clinical study, so milestone 3. Held behind a feature flag so that the behaviour is present and verifiable without being shown to study participants. Realised by dobVerification (force)", "3"],
    ["FR-AUT-013", "Upon successful verification, the software shall obtain a user token and shall associate that token with every subsequent request sent to the backend. The token shall expire after the defined period, after which the software shall require re-verification.", "RA 6.4; SRS-BE EX.3, AUT.8; SPTA 1.4, 6.1", "The backend SRS states 24 hours. Flagged at review as incorrect for this application and to be aligned; see the review register. Server-side verification of the token is required by FR-COM-010", "3"],
    ["FR-AUT-014", "The software shall enable the user to sign out. After sign-out, the software shall require the user to complete the verification process again before further use.", "SRS AUT.12; RA 6.4", "", "3"],
    ["FR-AUT-016", "The software shall guide the user through each authentication step and, on repeated failure, shall present support contact information.", "RA 4.16", "", "3"],
    ["FR-AUT-017", "On first launch, before the authentication process begins, the software shall present a short introductory sequence of no more than three screens introducing the application and the test, which the user may advance through or dismiss.", "Review comment", "Added at review. Content is part of the versioned set required by FR-TXT-004 and is subject to the reading level of FR-TXT-001. Distinct from the pre-test orientation raised as UX-08, which concerns what the user is told immediately before a test rather than on first launch", "4"],
    ["FR-AUT-007", "Where the phone number and invite code do not uniquely identify a single registered user, the software shall request the Date of Birth in order to identify which registered user is signing in.", "SRS AUT.7, AUT.9, AUT.11; RA 6.4; formerly BL-20, restored to its original identifier", "Future development, formerly BL-20. Reconciled at review: RA 6.4 retains FR-AUT-010, FR-AUT-012, FR-AUT-013, FR-AUT-014 and FR-SHR-003 in the body, all at milestone 3. FR-AUT-009 is withdrawn.", "5"],
    ["FR-AUT-011", "The software shall permit more than one user to be associated with the same phone number, each uniquely identified by their Date of Birth.", "SRS AUT.11; formerly BL-21, restored to its original identifier", "Future development, formerly BL-21. Household use on a shared phone number is therefore not supported until this is implemented. Confirmed at review that appUniqueIdentifier is to remain as configured today; see review register Q-10.", "5"],
    ["FR-AUT-015", "Where a test has been completed and more than one user is registered against the phone number, the software shall offer a 'switch user' function before a new test is started, which terminates the current session and returns the user to the authentication flow.", "SRS TSM.41; formerly BL-22, restored to its original identifier", "Future development, formerly BL-22. With FR-AUT-011, which it depends upon.", "5"],
    ["FR-AUT-020", "If a shared phone number is used to attempt a second test, the software shall prevent test initiation and prompt the user either to switch user or to contact support to obtain a new kit.", "SRS TSM.41; formerly BL-04", "Future development, formerly BL-04. Interacts with FR-AUT-015 and FR-KIT-004.", "5"],
    ["FR-AUT-021", "Where test data has not yet been successfully transmitted to the backend, the software shall not complete a sign-out, and shall inform the user that the transmission must finish first.", "Review comment; QACR-APP-SPEC-02", "Added at review. Signing out before the data has reached the backend discards the test irrecoverably. Complements FR-RDY-012, which retransmits data that did not arrive", "3"],
    ["FR-AUT-022", "Where the backend holds no identity for the authenticated user, the software shall require the user to complete the verification process again.", "Review comment; QACR-APP-SPEC-02", "Added at review. FR-AUT-013 requires re-verification when the token expires; this is a different trigger with the same outcome and nothing covered it", "3"],
    ["FR-AUT-024", "The software shall accept a one-time password entered automatically by the platform.", "Review comment; QACR-APP-SPEC-02", "Added at review. Both platforms", "4"],
    ["FR-AUT-023", "At phone-number entry, where the platform provides a means of offering the phone numbers held by the device, the software shall present it.", "Review comment; QACR-APP-SPEC-02", "Added at review, future development. Available on Android only. The step, its content and its outcome are identical on both platforms, so FR-PLT-006 is unaffected", "5"],
  ]
},

{
  code: "7",
  title: "Consent and Privacy Acknowledgement",
  intro: "Requirements for obtaining the user's acknowledgement of the Privacy Policy and Terms and Conditions before personal or health information is processed. Consent obligations attached to features deferred to a later revision are recorded in Appendix E.",
  reqs: [
    ["FR-CNS-001", "The software shall allow the user to view the Privacy Policy and the Terms and Conditions from the phone verification screen and from the main menu.", "SRS CON.1", "Realised by staticData.privacyUrl, staticData.termsUrl, consentUrl. Milestone rationale as FR-CNS-002", "4"],
    ["FR-CNS-002", "Upon entering the phone number, the software shall require the user to explicitly acknowledge acceptance of the Privacy Policy and Terms and Conditions by means of a mandatory checkbox.", "SRS CON.2", "Retained at milestone 4 by product decision: users do not go through phone verification at milestone 3, so no personal information is collected before the acknowledgement gate exists. See the decision log", "4"],
    ["FR-CNS-003", "If the user does not select a mandatory acknowledgement checkbox, the software shall prevent the user from proceeding with the requested action.", "SRS CON.4", "Milestone rationale as FR-CNS-002", "4"],
    ["FR-CNS-005", "Prior to initiating a chat with a doctor, the software shall require the user to explicitly acknowledge acceptance of the Privacy Policy and Terms and Conditions by means of a mandatory checkbox.", "SRS CON.3; formerly BL-01", "Future development, formerly BL-01. Depends on FR-SHR-013.", "5"],
    ["FR-CNS-006", "When the user elects to share test results with their primary care provider, the software shall present an additional acknowledgement prompt confirming acceptance of the Privacy Policy and Terms and Conditions.", "SRS CON.5; formerly BL-02", "Future development, formerly BL-02. Depends on FR-SHR-012.", "5"],
    ["FR-CNS-007", "The software shall record, and transmit to the backend, the identity and version of each policy document acknowledged, together with the time of acknowledgement.", "SRS-BE CON.1, CON.2; formerly BL-03", "Future development, formerly BL-03. Confirmed at review as future development. The backend SRS makes consent recording mandatory before a test starts as SRS-BE CON.1, so that document is to be relaxed to match; see review register Q-11.", "5"],
  ]
},

{
  code: "8",
  title: "Kit Identification and Validation",
  intro: "Requirements ensuring that only an authentic, unexpired, unused kit can be used for a test.",
  reqs: [
    ["FR-KIT-001", "The software shall verify the presence of the QR code on the Test Board. If the QR code is missing or damaged, the software shall prevent the user from completing a scan, display an explanatory error message, and instruct the user to contact support.", "SRS TSM.2, TSM.3; RA 4.19", "Realised by enabledNoQrBlock, featureFlags.qrDetectionUsingMLPackage", "3"],
    ["FR-KIT-002", "The software shall capture the QR code and transmit it to the backend to verify that the kit identifier is valid and that the kit has not previously been used. The backend shall maintain the record of used kit identifiers against which that check is made.", "SRS TSM.4; SRS-BE COM.8, COM.9, TSM.1; RA 7.1", "Register of used identifiers added from the backend SRS", "3"],
    ["FR-KIT-003", "The software shall validate the QR-code content against the defined kit-identifier template, and shall not return a test result unless a valid QR code has been read.", "RA 4.19", "", "3"],
    ["FR-KIT-004", "If the QR code is unidentified, or the kit identifier has already been used, the software shall invalidate the test at the point of scanning and display an explanatory error message. A second use of the same kit cannot be prevented before the assay has been run.", "SRS TSM.5, TSM.40; RA 7.1", "Revised per review: reuse is detected at scan rather than prevented up front, because the kit identifier is only read during the scan. RA 7.1 states the control as the same kit not being re-usable, which now means detected and blocked from producing a result. Also covers FR-KIT-006. Realised by enabledQrBlock and blockSubsequentTests.moreTestsThanKits", "3"],
    ["FR-KIT-007", "Where the user attempts to start a test within 24 hours after a previous test has completed, whether that test produced a result or was invalidated, the software shall present a message appropriate to the outcome of that previous test and shall require the user to confirm that they hold a new kit before the test flow begins. The message shall be presented on every such attempt until the user confirms it.", "RA 7.1", "Window confirmed at 24 hours and held as a configurable value. The window excludes its endpoint: an attempt at exactly 24 hours is not within it. Amended at the SPEC-04 review so that the message is presented on every attempt until it is confirmed rather than once. Guy also offered that the window may close on confirmation; that is deliberately not required here, because SPEC-03 settled that one acknowledgement stands until the next test completes, and the two end conditions differ with no observable difference to the user. Amended at the SPEC-03 review, which established that the product presents a different message according to whether the previous test produced a result or was invalidated, and that a single alert stating that a new kit is required does not describe it. Which cases exist is the product's, not this requirement's. Complements FR-KIT-004, which detects reuse of an already-used kit only at the point of scanning", "3"],
    ["FR-KIT-005", "The software shall automatically verify, from the kit identifier, that the kit is within its valid use period. If the kit has expired, the software shall prevent the test from proceeding and instruct the user to use a new kit.", "Product requirement; formerly BL-23, restored to its original identifier", "Future development, formerly BL-23. RA 7.25 has been removed from the Risk Analysis, and it was confirmed at review that the backend obligation follows the Risk Analysis, so SRS-BE TSM.2 and TSM.3 are to be relaxed to match; see review register Q-12. Realised by expiredKitDetection.", "5"],
    ["FR-KIT-008", "Where the kit-identifier check is refused for a reason the software cannot attribute to a condition it recognises, the software shall invalidate the test and shall present a message that does not state a specific reason.", "Product requirement; SPEC-03", "Added at the SPEC-03 review. FR-ALG-012 does this job for an invalid test and FR-RDY-014 for a refusal before a test starts; the kit-identifier check had no equivalent, and the product asserts an already-used kit for any refusal it cannot classify, which may be untrue and routes the user to the wrong support conversation. The reasons themselves are the backend contract and are not enumerated here", "3"],
    ["FR-KIT-009", "Where the software cannot read the kit identifier automatically, it shall offer the user the means to present the QR code for reading, and shall invalidate the test only once that has also failed.", "Product requirement; SPEC-03", "Future development. Added at the SPEC-03 review as a requirement of its own so that the automatic reading of FR-KIT-001 stays at milestone 3 and the manual route does not. Until this is implemented the automatic reads are the only ones, and a test with no readable identifier is invalidated after the scan", "5"],
    ["FR-KIT-010", "The backend shall be able to refuse a test attempted within a defined minimum interval of a previous test, and the software shall present the refusal.", "Product requirement; SPEC-03", "Future development. Distinct from FR-KIT-007, which asks the user to confirm and permits them to continue: this refuses outright. Added at the SPEC-03 review so that a capability the backend already has is in the record rather than reached by configuration alone", "5"],
  ]
},

{
  code: "9",
  title: "Guided Test Flow — Structure and Behaviour",
  intro: "The application is the primary means by which the user is guided through the physical test procedure. This section governs how that guidance is structured and how it behaves. What the guidance must actually say is specified separately in section 10.",
  reqs: [
    ["FR-FLW-001", "The software shall present the test procedure as a sequence of short, discrete steps, each requiring the user to confirm completion by activating a control provided for that purpose, and shall not advance to the next step without that confirmation.", "RA 4.1, 4.2", "The flow is presented as a chat-style exchange, one step at a time, which is the design decision behind the single-step visibility required by FR-FLW-004. How a blocking condition is presented is a user-interface decision and is not specified here", "1"],
    ["FR-FLW-002", "The software shall present, for each step, both textual guidance and a video or animated demonstration of the required action.", "SRS TSM.1; RA 4.1", "", "1"],
    ["FR-FLW-003", "Where the demonstration for a step is designated replayable, the software shall allow the instructions and demonstration for that step to be replayed at any time while the step is active.", "RA 4.1, 4.2", "Which steps are replayable is defined per step in the content set of FR-TXT-004. Confirmed at review that not every demonstration is replayable, following the current usability application", "1"],
    ["FR-FLW-004", "The software shall display only the instruction applicable to the current step, and shall not present instructions for steps that are not yet permitted. The instructions of completed steps shall remain available to the user while the flow continues, and the view shall follow each element of the flow as it is presented.", "RA 4.3", "", "1"],
    ["FR-FLW-005", "The software shall sequence the steps of the instructional flow in the order defined by the test procedure, and shall not permit a step to be reached out of that order.", "RA 4.1, 4.2", "", "1"],
    ["FR-FLW-007", "Where the application is in demonstration mode, it shall provide a means of advancing directly to a chosen section of the guided flow, and a means of advancing to the end of the section in progress. Those means may advance past anything the flow presents, including confirmation steps and time-dependent stages, and shall be reachable only by a deliberate gesture that a user would not perform in the course of taking a test, and not at all when the application is not in demonstration mode.", "Review comment", "Added at review for the milestone-1 demonstration. The gesture is to be specified; a sustained press on the start control or a device shake were the two suggested. At milestone 1 demonstration mode may be determined in the build; from milestone 2 it is determined by the configuration set of FR-CFG-001, which by then carries a real test partner as well. Complements FR-RES-006, which governs what may be presented as a result in that mode", "1"],
    ["FR-FLW-009", "Where a timed waiting period is long enough, the software shall present within the instructional flow a card that displays the time remaining and whose content changes as the period elapses. The thresholds determining whether the card is presented shall be fixed in the application. Its content shall be optional, in that not reading it can affect neither the conduct nor the validity of the test, and the card shall yield whenever the flow requires the user to act.", "Review comment; supports RA 4.18", "The mechanism is what is required: a modal within the chat, opened by the flow rather than by the user, whose content is a function of elapsed time in the current stage. The content itself, currently tips presented in sequence, is part of the approved content set under FR-TXT-004 and can change without changing this requirement", "1"],
    ["FR-FLW-008", "The software shall present the content of the instructional flow in spoken form as well as on screen, using recorded audio rather than synthesised speech, and shall provide a control by which the user can silence and restore it. Where the user silences it, the flow shall remain silent for the remainder of that test. The spoken flow and any demonstration in progress shall stop when the user confirms a step or the application ceases to be in the foreground, and neither shall resume without the user acting.", "Review comment; amended at the SPEC-04 review", "The spoken voice is a persona; naming it is a content decision under FR-TXT-004. Because the audio is recorded rather than generated from the displayed text, the spoken and written wording are separate artefacts that have to be released together, which is why FR-TXT-004 covers both. A further language means new recordings, not only new text", "1"],
    ["FR-FLW-006", "The software shall include or omit defined steps and sections of the guided flow according to a parameter resolved outside the application build, so that behaviour which is required to exist need not be presented to every user, and shall apply the same sequencing and confirmation rules to the steps that remain.", "Review comment; supports the milestone-3 placement of FR-AUT-010 and FR-AUT-012", "Added at review. This is the mechanism by which any step is made conditional; the Date of Birth confirmation withheld from clinical-study participants is one example, the explanatory video after a result another. The full set of conditions and the chat behaviour they drive is held in the chat bubbles specification, and the steps and governing parameters are to be listed before design verification", "3"],
    ["FR-FLW-010", "Each element of the instructional flow shall be presented after a defined interval, and where an element is accompanied by recorded audio that interval shall be the duration of that audio. The intervals shall be the same on every platform.", "SPEC-04 review", "The pace of the flow is most of what a user experiences during a waiting stage, and nothing previously stated it, so each platform held whatever value it happened to hold. The interval belongs to the flow engine and applies whatever the content is, which is why it is stated here rather than deferred to the content set of FR-TXT-004. It is also what makes a permission prompt follow the explanation of it rather than a fixed delay", "1"],
  ]
},

{
  code: "10",
  title: "User-Facing Content",
  intro: "Requirements governing what the application says, as distinct from how it behaves. They are grouped here so that instructional copy, warnings and result messaging can be drafted, reviewed for readability, and approved as a single body of content. Requirements FR-TXT-005 onwards follow the order in which the corresponding text is presented during a test.",
  reqs: [
    ["FR-TXT-001", "All user-facing text presented by the software, including component names, instructions, warnings, result descriptions and error messages, shall meet a Flesch-Kincaid reading level of grade 6 or lower.", "Glossary — Global Naming and Readability Rules", "Applies to every supported language", "2"],
    ["FR-TXT-002", "The software shall refer to kit components using only the approved user-facing component names defined in the Product Glossary, and shall not present internal or engineering sub-component names to the user.", "Glossary — Global Naming and Readability Rules", "User-facing set: Sample Collection Tool, Urine Collection Cup, Sample Pod, Mixing Cartridge, Test Board, coloured release button", "2"],
    ["FR-TXT-003", "The instructional content, warnings and result messaging presented by the software shall be consistent with the User Manual, and shall not instruct the user to act in a manner the User Manual contradicts.", "RA 4.7; derived", "", "3"],
    ["FR-TXT-004", "All user-facing content that is part of the core clinical test procedure, including the recorded audio of the spoken flow, shall be held under configuration control and released as a versioned content set, and the content-set version shall be recorded with each test record.", "RA 4.7; derived", "Written text and recorded audio are separate artefacts that say the same thing. Holding them in one versioned set is what stops the spoken and the displayed wording drifting apart between releases", "3"],
    ["FR-TXT-005", "The instructional flow shall direct the user to perform the test in a well-lit indoor location, avoiding direct sunlight, very dim lighting and uneven or mixed lighting.", "RA 7.11", "", "1"],
    ["FR-TXT-006", "The instructional flow shall instruct the user in the correct use of the Urine Collection Cup lid and in placing the cup in its designated location in the kit packaging.", "RA 7.4", "", "1"],
    ["FR-TXT-007", "The instructional flow shall guide the user to fill the Urine Collection Cup to or above the minimum fill line, and shall require the user to confirm that the fill line has been reached.", "RA 1.1, 7.3", "", "1"],
    ["FR-TXT-008", "The instructional flow shall guide the user through detaching the Sample Pod from the Urine Collection Cup, including the twist-and-pull motion required, and shall include a confirmation step.", "RA 7.6, 7.22", "", "1"],
    ["FR-TXT-009", "The instructional flow shall guide the user through inserting the Sample Pod into the Sample Tank port of the Mixing Cartridge, showing the correct port and orientation, and shall instruct the user to insert it until the audible or tactile confirmation is obtained.", "RA 7.7, 7.8, 7.26", "", "1"],
    ["FR-TXT-010", "The instructional flow shall instruct the user to remove the Peel-Off Seal from the Mixing Cartridge completely before connecting the cartridge to the Test Board, and shall require the user to confirm that it has been fully removed.", "RA 2.7; Glossary", "User-facing name TBD; see Appendix A.2", "1"],
    ["FR-TXT-011", "The instructional flow shall instruct the user to place the Test Board on a flat, stable surface before connecting the Mixing Cartridge, and to avoid applying pressure to the board surface at any point.", "RA 7.30; Glossary", "", "1"],
    ["FR-TXT-012", "The instructional flow shall provide a visual guide for aligning the Mixing Cartridge to the Test Board in the correct orientation.", "RA 7.27", "", "1"],
    ["FR-TXT-013", "The instructional flow shall guide the user through connecting the Mixing Cartridge to the Test Board, including the required hand position and applied force, so that the Plunger and Spring assembly is engaged and fluid transfer is initiated.", "RA 7.28; Glossary", "", "1"],
    ["FR-TXT-014", "The instructional flow shall guide the user through the required mixing or shaking action of the Mixing Cartridge and Test Board, including its duration.", "RA 7.10", "", "1"],
    ["FR-TXT-015", "The instructional flow shall specify the motion and depth required to operate the coloured release button, and shall state the tactile or audible cue that confirms it has been operated.", "RA 7.29; Glossary", "Approved user-facing name for the Transfer Valve. See the terminology appendix", "1"],
    ["FR-TXT-016", "The instructional flow shall direct the user to position themselves relative to the Test Board and the light source so that neither their hand, their body, nor any object casts a shadow over the Test Board during scanning.", "RA 7.15", "Complements the detection control in FR-IMG-009", "1"],
    ["FR-TXT-017", "The instructional flow shall provide disposal instructions for all used kit components and shall instruct the user to wash their hands after handling them.", "RA 7.30, 7.32", "The disposal content is specific to the QACR kit and does not carry over from the predecessor product, whose components differ", "1"],
    ["FR-TXT-019", "The results screen shall instruct the user not to make medical decisions on the basis of the result without consulting a healthcare professional, shall present explanatory material describing what the measurement represents and what the result category means, and shall state that the result is shared with a healthcare professional for further analysis and care.", "RA 7.17", "Content is fixed and released under the versioned content set required by FR-TXT-004. Unlinked from resultPortalMoreInfoUrl and resultsType at review", "1"],
    ["FR-TXT-020", "Each message presented when the software blocks an action shall name the condition detected, state the corrective action required, and provide support contact information, without disclosing personal or sensitive information.", "RA 4.15, 4.16; SRS ATT.6", "Governs the content of every blocking message in this document", "1"],
    ["FR-TXT-021", "The invalid-test messaging shall state the reason category returned for the test and the corrective action required, and shall instruct the user to repeat the test with a new kit.", "RA 4.3, 4.4", "Depends on FR-ALG-012", "3"],
    ["FR-TXT-022", "The software shall scale user-facing text with the text size selected in the device system settings, up to a defined maximum beyond which further increase is not applied. Within that range no text shall be truncated, overlapped or placed beyond reach.", "SPEC-04 review; accessibility", "Added at Guy's direction. The predecessor scales text from the system setting and caps it above a threshold, and the cap is the part that matters: without it a layout breaks at the largest settings. The maximum is a value to be set, like the other TBD values. Complements FR-TXT-001, which governs whether text can be understood; this governs whether it can be read", "3"],
    ["FR-TXT-023", "The software shall support the platform screen reader on user-facing content that the software does not itself read aloud, shall not have the screen reader duplicate content the software speaks, and shall not permit screen-reader operation to alter the conduct of a test or the timing of any stage.", "SPEC-04 review; accessibility", "Added at Guy's direction, with his two constraints written in rather than left to interpretation: the instructional flow is already spoken, so the screen reader applies where it is not, and it may not interfere with the test. Conformance to WCAG AA more broadly is Q-107 and is deliberately not claimed here", "4"],
  ]
},

{
  code: "11",
  title: "Test State Retention, Interruption and Cancellation",
  intro: "The test procedure spans several minutes and includes time-critical steps. These requirements define how the software preserves test state across interruptions, and how it behaves when a test is abandoned or the application is terminated.",
  reqs: [
    ["FR-STA-002", "If the test flow is interrupted by a transient event such as an incoming call, message, notification or screen lock, the software shall remain active in the background without terminating. While the application is not in the foreground the software shall not deliver instructional flow content, and on return shall resume delivery from the point the user had reached.", "SRS TSM.21; RA 4.1", "", "1"],
    ["FR-STA-003", "The software shall persistently retain the current test state throughout the test flow, including the completed steps and all recorded stage start times. If the user navigates away from the application without terminating it, the software shall permit the test flow to be resumed on return at the step that was active, shall make the applicable instructions and demonstration available for replay, and shall not apply any inactivity timeout while a test is active. A test becomes active when the user activates the control that starts it. Where no test is active, the software shall return the user to the start-up state after the applicable period of inactivity, discarding any instructional flow not yet begun.", "SRS TSM.22; RA 4.1, 4.2, 4.3, 4.4, 4.18", "Covers what was previously stated separately in FR-STA-001 and FR-STA-004", "1"],
    ["FR-STA-005", "If the software is interrupted during data upload, the software shall continue the upload in the background.", "SRS TSM.23", "", "1"],
    ["FR-STA-006", "The software shall not permit an active test to be resumed after the application has been terminated, whether by the user, by an operating-system action, by a software crash, or by a device restart.", "RA 7.19", "", "1"],
    ["FR-STA-007", "When the application is reopened following termination during an active test, the software shall identify the incomplete test, invalidate it, and inform the user that a new test must be performed using a new kit. A test whose capture completed and which awaits only transmission is not an incomplete test for this purpose.", "RA 7.19", "", "1"],
    ["FR-STA-008", "The software shall permit test cancellation only while the Urine Collection Cup has not been filled. Upon cancellation being requested after that step, the software shall warn the user that the current test cannot be resumed and that a new kit will be required, and shall require explicit confirmation.", "SRS TSM.19; RA 7.18", "Consistent with RA 7.3: once urine reaches the Capillary Tube it fills completely, so the sample is committed at cup fill", "3"],
    ["FR-STA-009", "If the user does not confirm cancellation, the software shall return to the active test flow at the step that was in progress.", "RA 7.18", "", "3"],
    ["FR-STA-010", "If cancellation is confirmed, the software shall invalidate the active test, prevent it from being resumed, and return the user to the start-up state.", "SRS TSM.19; RA 7.18", "", "3"],
    ["FR-STA-012", "The software shall prevent the device from dimming or locking the screen while the instructional flow is displayed.", "SPEC-04 review", "Prevention rather than tolerance: FR-STA-002 covers surviving a lock the user causes, and nothing previously required the device to be kept awake. A screen that darkens in the middle of a timed stage is the interruption most likely to occur, and holding it awake is also part of what the battery threshold of FR-RDY-007 is measured against", "1"],
  ]
},

{
  code: "12",
  title: "Timing Control",
  intro: "The assay is time-dependent at two stages. The first is the incubation period during which fluid is held in the Incubation Wells, released by the user operating the coloured release button. The second is the colour-evolution period in the Detection Wells that precedes the Test Board scan. The software is the sole means of enforcing both windows, which makes the requirements in this section safety-critical. All timing values are fixed in the application and are not configurable.",
  reqs: [
    ["FR-TIM-001", "For each time-dependent stage of the test flow, the software shall implement a defined start event, minimum duration, permitted completion window and expiry behaviour. These values shall be fixed in the application and shall not be configurable at run time.", "RA 4.18", "Values TBD, to be established by the timing-flex study. Confirmed at review that the study completes before milestone 3 and is not needed for milestones 1 and 2, so the milestone-1 build enforces these windows against provisional values", "1"],
    ["FR-TIM-002", "The software shall record and persistently retain the start time of each time-dependent stage.", "RA 4.3, 4.4, 4.18", "", "1"],
    ["FR-TIM-003", "Following application backgrounding, screen locking, or any other temporary interruption, the software shall calculate elapsed time from the retained start time and shall not restart the applicable timer.", "RA 4.3, 4.4, 4.18", "", "1"],
    ["FR-TIM-005", "The software shall display, for each active time-dependent stage, the time remaining until the next action is permitted and the time remaining before the permitted window expires.", "RA 4.3, 4.4, 7.9", "", "1"],
    ["FR-TIM-006", "The software shall measure the time elapsed from the user's confirmation of sample collection to the connection of the Sample Pod to the Mixing Cartridge. If the elapsed time exceeds the defined limit, the software shall invalidate the test.", "SRS TSM.6, TSM.7", "Limit TBD, fixed not configurable; currently specified as 30 minutes. An exceeded limit invalidates the test rather than blocking the step: confirmed at review, and FR-TIM-012 carries what the user is told and that a new kit is needed. Timed silently in the background: no countdown is shown, so that the user is not hurried", "3"],
    ["FR-TIM-007", "The software shall present the coloured release button instruction only after both the required Incubation Well residence time has elapsed and the preceding user instructions have been completed.", "RA 4.3, 7.9", "", "1"],
    ["FR-TIM-008", "The software shall prevent progression past any time-dependent stage before the applicable minimum time has elapsed, including preventing the Test Board from being scanned before the required colour-evolution period has elapsed. This shall not apply where the application is in demonstration mode, which produces no result for a patient.", "RA 4.18, 4.4", "Also covers FR-TIM-010", "1"],
    ["FR-TIM-009", "If the coloured release button step is not completed within the permitted timing window, the software shall invalidate the test and prevent continuation.", "RA 4.3", "", "1"],
    ["FR-TIM-011", "The software shall permit the Test Board to be scanned only within the validated scanning-time window, and shall invalidate the test if that window has expired.", "RA 4.4", "", "1"],
    ["FR-TIM-012", "When a test is invalidated on timing grounds, the software shall inform the user of the reason and instruct the user to repeat the test with a new kit.", "RA 4.3, 4.4", "", "2"],
    ["FR-TIM-014", "The software shall issue a local device notification when a timed window is about to expire, and shall do so only where the application is in the background at that time.", "Review comment; supports RA 4.3, 4.4", "Local notification, not a backend push; see FR-COM-009", "4"],
    ["FR-TIM-004", "The software shall derive elapsed time from a time source that is not affected by user modification of the device clock or time zone.", "RA 4.18; formerly BL-24, restored to its original identifier", "Future development, formerly BL-24. Until implemented, the timing windows in section 12 can be defeated by changing the device clock, since elapsed time is derived from a source the user can alter. RA 4.18 relies on the timers being enforceable.", "5"],
  ]
},

];
