// QACR Mobile App - Functional Requirements data (part 2 of 2) - Rev 0.5
// Row format: [id, requirement, source, notes, priority]

module.exports = [

{
  code: "13",
  title: "Image Capture and Validation (IVTS)",
  intro: "The Image Validation Transfer System (IVTS) is the principal control mitigating variation between smartphone models, camera conditions and user technique. It operates on the Color Print, which provides optical neutralisation and a standardised reference colour spectrum, viewed through the transparent Top-Plate. Validation happens in two stages: the QCR stage, which runs in real time while the user is framing the board, and the algorithm pipeline, which runs on the captured set. A condition detected at either stage is reported to the user, who may scan again; only exhaustion of the scanning window invalidates the test. The stages themselves are specified in the IVTS and algorithm documents.",
  reqs: [
    ["FR-IMG-001", "The software shall validate every captured frame against the predefined IVTS acceptance thresholds, and shall permit a result to be produced only where the acquired information meets those thresholds.", "RA 4.8, 4.10, 4.11, 4.12", "Thresholds and the minimum number of valid frames are defined in the IVTS specification and fixed in the application. Unlinked from minValidFrames at review", "1"],
    ["FR-IMG-002", "The software shall capture the Test Board only where the Color Print reference markers are detected and visible within acceptance criteria and the Test Board is entirely within the camera frame, and shall block the scan where either condition is not met.", "SRS TSM.8, TSM.9, TSM.10; RA 3.11", "Also covers FR-IMG-003", "1"],
    ["FR-IMG-004", "The software shall detect whether the smartphone is too far from the Test Board. If so, the software shall prevent the user from initiating a scan and display an explanatory error message.", "SRS TSM.11; RA 7.12", "", "1"],
    ["FR-IMG-005", "The software shall detect whether the smartphone is too close to the Test Board. If so, the software shall prevent the user from initiating a scan and display an explanatory error message.", "SRS TSM.12; RA 7.12", "", "1"],
    ["FR-IMG-006", "The software shall detect whether the smartphone is positioned at an acute angle relative to the Test Board. If so, the software shall prevent the user from initiating a scan and display an explanatory error message.", "SRS TSM.13; RA 7.14", "", "1"],
    ["FR-IMG-007", "The software shall detect whether the image is too dark. If so, the software shall prevent the user from initiating a scan and display an explanatory error message.", "SRS TSM.14; RA 7.11", "", "1"],
    ["FR-IMG-008", "The software shall detect whether the image is saturated. If so, the software shall prevent the user from initiating a scan and display an explanatory error message.", "SRS TSM.15; RA 7.11", "", "1"],
    ["FR-IMG-009", "The software shall use the Color Print reference anchors to detect shadow conditions across the Test Board, and shall block the scan where shadow conditions fall outside the validated thresholds.", "RA 7.15", "", "1"],
    ["FR-IMG-010", "The software shall validate focus and motion in real time during framing, and shall capture an image only where image-quality thresholds are met.", "RA 7.16", "", "1"],
    ["FR-IMG-011", "Upon capture of the Test Board image, the software shall validate image clarity. If the image is too blurry, the software shall display an explanatory message and instruct the user to try again.", "SRS TSM.25; RA 7.16", "", "1"],
    ["FR-IMG-013", "The software shall provide real-time guidance during scanning that directs the user towards a valid distance, angle and framing position.", "RA 7.12, 7.14", "", "1"],
    ["FR-IMG-014", "Each QCR condition and each IVTS boundary condition shall produce a distinct user message that names the condition detected and states the corrective action required.", "RA 7.11–7.16", "Content per FR-TXT-020", "1"],
    ["FR-IMG-015", "Where IVTS validity thresholds are not met, the software shall invalidate the captured image and permit the user to re-scan. If the permitted scanning window expires without a sufficient number of valid frames, the software shall invalidate the test rather than produce a result of reduced reliability.", "RA 4.8, 4.10, 4.12", "", "1"],
    ["FR-IMG-016", "The software shall use the standardised reference colour spectrum of the Color Print to normalise the captured image before colorimetric values are derived from the Detection Wells.", "Glossary; RA 4.8", "Whether a raw or raw-equivalent representation is used, and whether normalisation happens on the device or in the backend, is undecided. It will not be the mechanism the earlier localLearnedRawEnabled flag implemented. See review register Q-24", "1"],
    ["FR-IMG-022", "During a timed waiting period of the test flow the software shall present a practice scan as a step of the instructional flow, which the user passes through in order to continue. A practice scan shall behave as a scan of the Test Board does, including the QCR stage, the IVTS boundary detection, the QR-code validation and the guidance, shall not apply the scanning-window limit, shall end on a limit of its own rather than on the end of the waiting period in which it began, shall not register the kit identifier as used, and shall neither produce a result nor contribute any image to the test record.", "Review comment; supports RA 7.11 to 7.16", "It exists so that a user meets the scanning interaction, and any difficulty with it, while there is still time to resolve it rather than inside the scanning window. Offered during the first timed stage, where the waiting period is longest. The kit checks run read-only here, so a user who practises on the kit they are about to test with cannot spend it. Validation against the identifier template, FR-KIT-003, arrives at milestone 3. The used-kit check, FR-KIT-004, arrives at milestone 3 as well. Until then a practice scan exercises framing and guidance only", "1"],
    ["FR-IMG-023", "After a complete frame set has been captured the software shall indicate that the images are being prepared and evaluated, and shall then either continue the flow or report a boundary condition and offer the user the opportunity to scan again.", "Review comment", "Added at review. The preparation and evaluation stage takes long enough to need a state of its own; without it the user is left on a viewfinder with nothing happening", "1"],
    ["FR-IMG-024", "During capture the software shall deliver the scan guidance in spoken form as it changes, so that a user whose attention is on the Test Board rather than on the screen is guided without having to look.", "Review comment; supports RA 7.12, 7.14, 7.16", "", "1"],
    ["FR-IMG-021", "The software shall detect specular reflection on the Test Board surface, and shall block the scan where it falls outside the validated thresholds.", "Review comment; supports RA 7.11, 7.15", "Added at review as a further IVTS boundary condition alongside the six in this section. The Risk Analysis trace is to be confirmed when the analysis is next revised: specular reflection is a lighting condition, so RA 7.11 and RA 7.15 are the candidates. Message content per FR-IMG-014", "1"],
  ]
},

{
  code: "14",
  title: "Camera Control and Image Acquisition",
  intro: "Requirements governing how the camera is driven during a scan, in order to obtain colorimetric data that is comparable across supported smartphone models. The specific frame recipe and adjustment logic are properties of the IVTS design; this section requires that the software implement whatever the IVTS specification defines, rather than fixing those parameters here.",
  reqs: [
    ["FR-CAM-001", "The software shall acquire, for each scan, the frame set defined by the IVTS specification, including the number of frames, the torch state applied to each, and any platform-specific additional frames, and shall transmit the complete set for analysis.", "SRS PER.2, PER.3; Glossary — Smartphone Application", "Also covers FR-IMG-017. The frame set is defined by the IVTS specification and fixed in the application. Unlinked from featureFlags.selectBestCameraEnabled at review", "1"],
    ["FR-CAM-002", "The software shall apply the camera adjustments defined by the IVTS specification in response to a raised boundary condition, including white-balance adjustment on devices that support it and exposure adjustment where the image is too dark or too bright.", "SRS PER.4, PER.5", "Priority TBD. Realised by featureFlags.manualWhiteBalanceEnabled, manualExposureEnabled, customToneMappingEnabled", "TBD"],
    ["FR-CAM-003", "The software shall record, with each captured image, the camera parameter set that was applied, including torch state, exposure, white balance and any tone-mapping configuration.", "RA 4.8", "Required for IVTS traceability", "1"],
    ["FR-CAM-004", "If the camera becomes unavailable or returns an invalid frame during capture, the software shall abort the capture, inform the user, and permit the scan to be re-attempted within the permitted scanning window.", "RA 4.10", "", "3"],
  ]
},

{
  code: "15",
  title: "Data Transmission and Backend Communication",
  intro: "Requirements for the interface between the application and the backend, and for the handling of interrupted or failed communication. The transport requirements carry most of the threat-analysis controls for data in transit, and FR-COM-005 and FR-COM-010 record the principle that the backend treats everything the application sends as untrusted.",
  reqs: [
    ["FR-COM-001", "The software shall interface with the backend via HTTPS over TCP/IP using TLS 1.2 or above, with strong cipher suites, SSL chain verification and strong session identifiers. The software shall refuse to establish a connection negotiated below TLS 1.2.", "SRS EX.1; RA 5.1; SPTA 1.1, 2.11, 4.4, 4.5", "TLS floor and cipher requirements added from the threat analysis", "3"],
    ["FR-COM-002", "The software shall enforce certificate pinning, so that connections are established only with servers presenting the expected SSL/TLS certificate, and shall reject a connection presenting any other certificate.", "SRS ATT.1; SPTA 4.4, 4.12", "SPTA 4.12 is the highest-scoring threat mitigated by the application alone, at 16 gross", "3"],
    ["FR-COM-003", "Upon successful Test Board capture, the software shall transmit the acquired test data to the backend and shall display an indication confirming the upload status.", "SRS TSM.17, TSM.26", "", "1"],
    ["FR-COM-004", "The software shall include an integrity check with each transmitted payload so that incomplete or corrupted transmission is detectable by the backend.", "RA 5.1", "", "1"],
    ["FR-COM-005", "The backend shall validate received test data and shall reject transmissions that are incomplete, malformed or nonconforming to the defined data format, treating all data received from the application as untrusted.", "RA 5.1; SPTA 2.4", "Backend. SPTA 2.4 relies on this as the compensating control for a modified or instrumented application", "1"],
    ["FR-COM-006", "If communication is lost during data upload, the software shall notify the user, retain the test data, initiate an automatic retry, and resume transmission once connectivity is restored.", "SRS TSM.18; RA 5.2, 5.3; SPTA 5.2, 5.3", "", "3"],
    ["FR-COM-007", "Upon successful data upload and backend acknowledgement, the software shall permit the user to conclude the test process and shall delete all related test data from the smartphone.", "SRS TSM.24, TSM.27", "", "3"],
    ["FR-COM-008", "If the backend returns an error, the software shall display an explanatory error message and provide instructions on the next steps available to the user.", "SRS TSM.29", "Content per FR-TXT-020", "1"],
    ["FR-COM-009", "The software shall generate local device notifications without dependence on backend connectivity, for the purposes defined in FR-TIM-014.", "Review comment", "Backend push notifications are future development as FR-COM-013", "4"],
    ["FR-COM-012", "The software shall request the permission required to present device notifications, shall precede the platform permission prompt with an explanation of why notifications are wanted, and shall not prevent a test from being started, completed or reported if permission is refused.", "Review comment; supports FR-TIM-014", "Added at review. FR-TIM-014 and FR-COM-009 cannot function without this permission and nothing previously required it to be asked for. Milestone follows those two requirements", "4"],
    ["FR-COM-010", "The backend shall verify the identity and authorisation carried by every incoming request, and shall reject any request that is unauthenticated, unauthorised for the resource addressed, or attempting to act on a patient record other than the one associated with the verified user.", "SPTA 6.1; RA 6.4", "Backend. New from the threat analysis. The application obligation is FR-AUT-013", "3"],
    ["FR-COM-011", "The software shall request the result for a completed test from the backend, shall present a waiting state until a result or an invalid-test outcome is received, and shall inform the user how the result will reach them if none is received within the defined period.", "Review decision CR-17; supports SRS TSM.28", "Added at review. FR-RES-001 presumed receipt: no requirement covered the application-side act of requesting a result. The waiting period is a system parameter and is not yet valued; see the review register", "1"],
    ["FR-COM-013", "The software shall support the receipt of push notifications from the backend system.", "SRS OTH.1; formerly BL-05", "Future development, formerly BL-05. Distinct from the local notifications in FR-TIM-014 and FR-COM-009, which are in this version.", "5"],
  ]
},

{
  code: "16",
  title: "Analysis, Quality Control and Algorithm Version Management",
  intro: "Requirements on the analysis performed on the acquired data, and on the controls that ensure each exam is processed by approved algorithm versions and that invalid assay runs never yield a reported result. Albumin is measured over two stages, incubation followed by detection; creatinine is measured at the detection stage only.",
  reqs: [
    ["FR-ALG-001", "The backend shall determine albumin concentration, creatinine concentration and the albumin-to-creatinine ratio from the validated image data, using an algorithm version approved for the applicable system configuration.", "RA 4.21, 4.22", "Algo", "3"],
    ["FR-ALG-002", "The system shall maintain a controlled mapping between supported software configurations and approved algorithm versions, and shall analyse an exam only using an algorithm version approved for the applicable configuration.", "RA 4.22", "Backend", "3"],
    ["FR-ALG-003", "The backend shall validate that the mobile algorithm version and the backend algorithm version assigned to an exam are an approved combination, and shall prevent analysis where either version is missing or unsupported, or where the combination is not approved.", "RA 4.22", "Backend. TBD, and may become obsolete when the Risk Analysis is next revised", "TBD"],
    ["FR-ALG-004", "The system shall record, for each exam, the mobile and backend algorithm versions, the application version and the backend version used to produce the result, together with a timestamp, the device identifier, the patient identifier, the reported values, the raw results, error records and diagnostic metadata.", "RA 4.22; SRS-BE LOG.1, LOG.2", "Backend. Record contents stated from the backend SRS", "2"],
    ["FR-ALG-005", "The system shall perform standard-curve quality control on each test and shall block the reporting of a result where quality control fails.", "RA 3.6, 3.7, 7.33, 7.35", "Algo", "3"],
    ["FR-ALG-006", "The system shall evaluate the recovery and blank wells within the Detection Wells in order to detect foreign or interfering substances and discoloration of the diluted urine, and shall block the reporting of a result where the acceptance criteria are not met.", "RA 1.6, 7.20; Glossary", "Algo", "3"],
    ["FR-ALG-007", "The system shall detect an incomplete assay run, including the condition in which both albumin and creatinine are below the limit of detection, shall invalidate the test, and shall cause the application to prompt the user to repeat the test with a new kit.", "RA 1.1, 1.3, 1.7, 2.1, 2.4, 2.5, 2.6, 2.9, 3.1, 3.2, 3.3, 7.6, 7.7, 7.8, 7.22, 7.29, 7.34", "Algo; surfaced in app", "2"],
    ["FR-ALG-008", "The system shall detect that the urine sample was not introduced into the buffer, and shall detect that insufficient fluid reached the Detection Wells, and shall block the reporting of a result where either condition is present.", "RA 3.8, 7.9, 7.30, 7.36", "Algo. TBD, to be settled when the Risk Analysis is next revised. Out-of-sequence assay signatures cannot be detected; RA 3.8 and RA 7.36 currently have no other software control", "TBD"],
    ["FR-ALG-009", "The system shall detect insufficient colour output in the standard curves and shall block the reporting of a result where the acceptance criteria are not met.", "RA 3.5, 3.6, 3.7", "Algo; albumin standards AS1–AS4, creatinine standards CS1–CS4", "2"],
    ["FR-ALG-010", "The result payload returned to the application shall distinguish unambiguously between a valid quantitative result and an invalid test, and the application shall not present a numeric value for an invalid test under any condition.", "RA 4.21; derived", "", "2"],
    ["FR-ALG-011", "The system shall identify results that fall outside the claimed measuring range and shall convey that condition to the application for presentation.", "RA 4.21", "Algo; presentation per FR-RES-004", "3"],
    ["FR-ALG-012", "The result payload shall include a reason category for each invalid test, drawn from a defined enumeration, sufficient for the application to inform the user of the corrective action required.", "RA 4.3, 4.4", "Dependency of FR-TXT-021", "2"],
  ]
},

{
  code: "17",
  title: "Result Presentation",
  intro: "Requirements governing what the application displays when a result is returned. The wording of the accompanying interpretation guidance is specified in section 10.",
  reqs: [
    ["FR-RES-001", "After receiving results from the backend, the software shall display them to the user. The backend shall transmit the result for the exam identified in the request.", "SRS TSM.28; SRS-BE COM.7, COM.11", "", "1"],
    ["FR-RES-002", "The software shall present the albumin-to-creatinine ratio both as a numerical value and as a result category.", "RA 7.17", "Presentation is fixed: the ratio only, as a value and a category. Unlinked from resultsType and staticData.showAcrResultOnly at review. Presentation of the albumin and creatinine values is future development; see FR-RES-007", "1"],
    ["FR-RES-003", "The software shall present the units of measurement applicable to each reported value.", "Derived; supports RA 7.17", "Not required by RA 7.17; retained as a product decision", "1"],
    ["FR-RES-004", "Where the result falls outside the claimed measuring range, the software shall present that condition rather than an unqualified numeric value.", "RA 4.21", "", "2"],
    ["FR-RES-005", "For an invalid test, the software shall present an invalid-test outcome rather than any numeric value.", "RA 4.3, 4.4; FR-ALG-010", "Messaging per FR-TXT-021", "1"],
    ["FR-RES-006", "Where the application is in demonstration mode for the test being performed, the software shall present a result drawn from a fixed demonstration payload rather than from an analysed test, shall not present that result as a clinical result, and shall make the demonstration state evident wherever that result is presented.", "Review decision CR-07, CR-08", "Added at review so that milestone 1 can present a result before any of the analysis pipeline exists. Demonstration mode is a state the backend returns with the configuration before a test starts, not a separate build, so the same artefact that ships to patients can be placed in it — which is why the evidence of the state must be visible to the user and why FR-CFG-004, server-side enforcement of demonstration behaviour, matters more than its deferral suggests. In demonstration mode no algorithm version is exercised, which is why quantitation and the approved-version mapping are not needed at milestone 1", "1"],
    ["FR-RES-007", "The software shall present the albumin and creatinine values in addition to the albumin-to-creatinine ratio.", "Review item R-03; formerly BL-12", "Future development, formerly BL-12. Constrained by staticData.showAcrResultOnly, currently true. See FR-RES-002.", "5"],
  ]
},

{
  code: "18",
  title: "Results Access Protection",
  intro: "Requirements controlling access to the results center after a test has been completed.",
  reqs: [
    ["FR-ACC-001", "The software shall restrict access to the post-test results center to users who have set a PIN code.", "SRS TSM.30; SPTA 1.4, 1.7", "", "4"],
    ["FR-ACC-002", "If a PIN code has not been set, the software shall prompt the user to create one before granting access to the results center. The backend shall report whether a PIN is registered for the user profile.", "SRS TSM.31; SRS-BE PIN.1; SPTA 1.4", "", "4"],
    ["FR-ACC-004", "The software shall restrict PIN code entry to numeric values only, of four digits.", "SRS TSM.32; SPTA 2.1", "Length is four digits and the attempt limit is five, both settled at review. Enforced server-side per the backend SRS", "4"],
    ["FR-ACC-005", "If the maximum number of incorrect PIN attempts is reached, the software shall deny access to the results center and instruct the user to contact support. The backend shall maintain the failure counter and enforce the limit.", "SRS TSM.33; SRS-BE PIN.2, PIN.4, PIN.5", "Limit is five consecutive failed attempts per the backend SRS, enforced server-side", "4"],
    ["FR-ACC-006", "If the user has not set a PIN code within the defined period after test completion, the software shall lock PIN setup and direct the user to contact support, who may reset it following identity re-verification. The backend shall reject any PIN setup request received after that period.", "SRS TSM.34; SRS-BE PIN.6; SPTA 1.7", "Period is 24 hours, confirmed by both the threat analysis and the backend SRS, and enforced server-side. The support reset path is deferred as FR-ACC-008", "4"],
    ["FR-ACC-009", "After 15 minutes of inactivity in the results center, the software shall return the user to the home screen and shall require the PIN to be entered again before the results center can be re-entered. The backend shall invalidate the session on the same interval.", "SPTA 1.7; SRS-BE PIN.7", "The 15-minute value comes from the threat analysis and is confirmed by the backend SRS, which enforces it server-side. Applies to the results center only; FR-STA-003 bars any inactivity timeout during an active test. Restated at review: re-entry is by PIN rather than Date of Birth, since the Date of Birth is no longer requested at login", "4"],
    ["FR-ACC-003", "The software shall integrate PIN setup into the test workflow, so that the user is prompted to set a PIN as part of completing the test.", "RA 7.21; formerly BL-25, restored to its original identifier", "Future development, formerly BL-25. With FR-ACC-007 and FR-ACC-008 also deferred, RA 7.21 has no software control in this version; severity is 1 and the consequence is loss of access to results beyond the initial view.", "5"],
    ["FR-ACC-007", "After successful PIN setup, the software shall offer the user the option to enable biometric authentication for results-center access on devices that provide it.", "SRS TSM.35; RA 7.21; formerly BL-26, restored to its original identifier", "Future development, formerly BL-26. With FR-ACC-003 and FR-ACC-008; see the note against FR-ACC-003.", "5"],
    ["FR-ACC-008", "The software shall support PIN reset by customer support following identity re-verification.", "RA 7.21; formerly BL-27, restored to its original identifier", "Future development, formerly BL-27. With FR-ACC-003 and FR-ACC-007; a user who forgets their PIN has no recovery path until this is implemented.", "5"],
  ]
},

{
  code: "19",
  title: "Results Center and the Main Menu",
  intro: "Two things the user reaches outside the test flow. The results center is a screen of its own, giving access to previous results; access to it is controlled by section 18. The main menu, presented as a hamburger on the home screen, is the route to the information pages an authenticated user may need at any time. Several of those pages are required elsewhere in this document for a specific moment in the flow; the requirements here add the obligation that they are also reachable from the menu.",
  reqs: [
    ["FR-PRT-001", "The software shall provide a results center as a screen of its own, giving the authenticated user ongoing access to their most recent result and stating the date on which that test was performed. The backend shall transmit that result on request.", "Product requirement; SRS-BE COM.12", "Split at review: the results center main screen shows the most recent result and is milestone 3; the history of earlier results is a separate screen and is deferred as FR-PRT-015. Whether invalidated tests appear, and whether results belonging to another registered user on the same phone number are excluded, are to be specified; the second bears on RA 6.4", "3"],
    ["FR-PRT-007", "The software shall present a control on the home screen by which an authenticated user can open the results center directly, separately from the main menu.", "Product requirement", "Added at review. A second entry point to the results center alongside the main menu of FR-PRT-002, so that a returning user reaches their result without going through a menu", "3"],
    ["FR-PRT-002", "The software shall present a main menu, reached from a hamburger control on the home screen, available to an authenticated user at any time outside an active test.", "Product requirement", "The container for FR-PRT-003 to FR-PRT-005, and for the deferred FAQ entry FR-SUP-001. Priority follows the menu items required at milestone 3", "3"],
    ["FR-PRT-003", "The main menu shall give access to an About screen presenting the regulatory information required for the device.", "Product requirement", "Content to be specified by regulatory. Subject to FR-TXT-002 for component naming; whether the grade-6 reading level in FR-TXT-001 applies to mandated regulatory wording is to be confirmed", "3"],
    ["FR-PRT-004", "The main menu shall give access to support contact, enabling an authenticated user to reach support without starting a test.", "Product requirement; SRS STM.10", "Adds menu access to the support route required by FR-SUP-002. In-application support chat is deferred as FR-SUP-004", "3"],
    ["FR-PRT-005", "The main menu shall give access to the Privacy Policy and the Terms and Conditions, presented in an in-application web view.", "Product requirement; SRS CON.1", "States the presentation mechanism and the menu route for FR-CNS-001, which requires the documents to be viewable. Realised by staticData.privacyUrl and staticData.termsUrl", "4"],
    ["FR-PRT-008", "The software shall allow the user to open a configured web page from the application.", "SRS TSM.43; formerly BL-10", "Future development, formerly BL-10. The survey web view in FR-SUR-001 is in this version and is separate from this item.", "5"],
    ["FR-PRT-009", "The results center shall enable the user to view the results letter.", "Product requirement; formerly BL-16", "Future development, formerly BL-16. Part of the results center screen required by FR-PRT-001. Overlaps FR-SHR-015, which covers generation, saving and email sharing as one item; the two should be merged when the milestone-5 set is reconciled.", "5"],
    ["FR-PRT-010", "The results center shall enable the user to share the results letter.", "Product requirement; formerly BL-17", "Future development, formerly BL-17. Part of the results center screen; overlaps FR-SHR-015 as above.", "5"],
    ["FR-PRT-011", "The results center shall enable the user to view further information about their result.", "Product requirement; formerly BL-18", "Future development, formerly BL-18. Part of the results center screen. Realised by resultPortalMoreInfoUrl, already set for normal and abnormal results. Distinct from the explanatory material required at the point of result delivery by FR-TXT-019, which is in scope now.", "5"],
    ["FR-PRT-012", "The software shall present a post-test lobby as the state of the home screen following a successful test, comprising a checklist of post-test actions each with an open or closed presentation state and a done or not-done completion state, and a control that navigates to the results center. The lobby shall be shown for a configured period after the most recent result, after which the home screen returns to its regular state.", "Post test lobby redesign spec (lobby 4); formerly BL-36", "Future development, formerly BL-36. The screen and its mechanics. Realised by staticData.resultsLobbyDuration, currently 90 days. Detailed behaviour, including the four state combinations per item, the collapse and expand rules and the row confirming a test was performed, is specified in the lobby spec and is not reproduced here.", "5"],
    ["FR-PRT-013", "The post-test lobby shall present the post-test actions defined for the result type, comprising sharing the results letter and booking an appointment for a positive result, sharing the doctor's information according to the primary care provider questionnaire, a simplified layout without actions for a normal result, and a control to start a new test.", "Settled at review: the application may retain a non-revealing indicator of recent result positivity and use that to decide what to present, following the existing kidney application, rather than depending on the backend to supply positivity. Post test lobby redesign spec (lobby 4); formerly BL-37", "Future development, formerly BL-37. The action set. Gated per partner by staticData.additionalResultsCTA for the appointment action. Requires result positivity to be available to the application, which the lobby spec records as an open backend dependency. Sharing depends on FR-SHR-012 and FR-PRT-009; starting a new test is subject to FR-KIT-007.", "5"],
    ["FR-PRT-014", "The results center shall omit a next-steps section, shall present a view-results-letter control within its further-information area, and shall present the result explanation collapsed when the results center is opened.", "Post test lobby redesign spec (lobby 4), phase 2; formerly BL-39", "Future development, formerly BL-39. Results center changes accompanying the lobby redesign. Interacts with FR-PRT-001, FR-PRT-009 and FR-PRT-011.", "5"],
    ["FR-PRT-015", "The results center shall provide a results history screen presenting the user's last five results, reachable only where more than one result exists.", "Product requirement; formerly part of FR-PRT-001; formerly BL-42", "Future development, formerly BL-42. Separated from FR-PRT-001 at review. The results center main screen shows the most recent result and is milestone 3; this history screen is future development. Realised by portalResultsHistoryEnabled.", "5"],
  ]
},

{
  code: "20",
  title: "Result Routing and Provider Communication",
  intro: "Requirements ensuring the result reaches the correct provider and is recorded against the correct patient. In this revision the result reaches the provider through the backend; the user-initiated sharing and provider-contact features are deferred, and are recorded in Appendix E.",
  reqs: [
    ["FR-SHR-001", "The backend data model shall be segmented by partnering organisation, enforcing logical data isolation so that records belonging to one health provider are inaccessible to another, and each patient shall be mapped to a single medical provider organisation, in a manner that supports both prescription generation and the return of results to the prescribing doctor.", "RA 6.3; SRS-BE LOG.3", "Backend. Multi-tenancy isolation stated explicitly from the backend SRS", "3"],
    ["FR-SHR-002", "The system shall route test result data according to the medical provider organisation associated with the patient.", "RA 6.3", "Backend", "3"],
    ["FR-SHR-003", "The backend shall map each test result to the patient record associated with the verified user token used to submit the test.", "RA 6.4", "Backend; see FR-AUT-013", "3"],
    ["FR-SHR-004", "Each medical provider organisation shall have a separate integration setup and configuration.", "RA 6.3", "Backend", "3"],
    ["FR-SHR-005", "Integration protocols with medical providers shall be based on industry standards, using HL7 for data integrity. The provider-specific protocol and data mapping shall be documented and agreed with the provider before implementation, and access shall be denied to unauthorised addresses.", "RA 6.1; SRS-BE EX.2, EX.5", "Backend. Address restriction added from the backend SRS. HISP delivery to primary care providers was separated at review and is deferred as FR-SHR-017", "3"],
    ["FR-SHR-006", "The provider communication protocol shall include handshake and acknowledgement mechanisms that verify successful transmission of test result data.", "RA 6.2", "Backend", "3"],
    ["FR-SHR-007", "The backend shall identify failed provider transmissions and shall retry transmission when communication with the medical provider becomes available.", "RA 6.2", "Backend", "3"],
    ["FR-SHR-008", "The backend shall reject malformed or nonconforming provider transmissions.", "RA 6.1", "Backend", "3"],
    ["FR-SHR-011", "The configuration shall state, for each partner, whether doctor-to-patient engagement takes place within the application or outside it, and the software shall present the corresponding post-result journey.", "Review item R-11", " Determines whether the future-development chat and consultation features, FR-SHR-013 and FR-SHR-014, are in scope for a given partner", "TBD"],
    ["FR-SHR-012", "The software shall provide the user with an option to share test results with their primary care provider.", "SRS CON.5, TSM.46; formerly BL-06", "Future development, formerly BL-06. Consolidates two deferred requirements.", "5"],
    ["FR-SHR-013", "The software shall enable the user to initiate a chat with a doctor before starting a test or after completing one.", "SRS TSM.39; formerly BL-08", "Future development, formerly BL-08. Scope determined by FR-SHR-011.", "5"],
    ["FR-SHR-014", "The software shall allow the user to call a primary care provider or care team using a configured phone number.", "SRS TSM.42; formerly BL-09", "Future development, formerly BL-09.", "5"],
    ["FR-SHR-015", "The software shall allow the generation of a results letter in PDF format, and shall allow the user to save it to the smartphone and share it by email.", "SRS TSM.36, TSM.37, TSM.38; SRS-BE COM.10; formerly BL-11", "Future development, formerly BL-11. Confirmed for future development. The backend SRS requires letter generation and transmission as SRS-BE COM.10.", "5"],
    ["FR-SHR-016", "Where completing a results-sharing action requires an application outside this one, the software shall hand off to that application. Hand-off shall be limited to applications explicitly configured for that purpose, shall be initiated only by an action the user has taken, and shall pass no more information than the sharing action requires.", "SRS TSM.44; review register Q-20; formerly BL-41", "Future development, formerly BL-41. Stated generally rather than naming a particular application. The guard is deliberate: SRS TSM.44 permitted launching arbitrary applications, which had no stated purpose and no security rationale.", "5"],
    ["FR-SHR-017", "The provider integration shall support the HISP protocol for secure delivery of results to primary care providers.", "RA 6.1; SRS-BE EX.2, EX.5; formerly part of FR-SHR-005; formerly BL-43", "Future development, formerly BL-43. Separated from FR-SHR-005 at review. HL7 and the documented per-provider mapping remain in the body at milestone 3; HISP delivery is future development.", "5"],
    ["FR-SHR-018", "The software shall determine whether a configured sharing application is present on the device, and shall present the sharing options that apply accordingly.", "Review comment; supports FR-SHR-016; formerly BL-44", "Future development, formerly BL-44. With the rest of user-initiated sharing. Detection is limited to applications explicitly configured for sharing, which is the same allow-list FR-SHR-016 restricts hand-off to; neither platform permits enumerating what else is installed.", "5"],
  ]
},

{
  code: "21",
  title: "Support and Help",
  intro: "Requirements for the routes by which a user obtains assistance, including from within a blocked or failed flow.",
  reqs: [
    ["FR-SUP-002", "The software shall enable the user to contact the support team by telephone or by email.", "SRS STM.10; SPTA 5.2", "Split per review. Realised by staticData.supportNumber and staticData.supportEmail. SPTA 5.2 relies on support offering workarounds during a third-party outage", "3"],
    ["FR-SUP-003", "Where the software blocks the user from proceeding and the user cannot resolve the condition themselves, it shall present support contact information.", "RA 4.15, 4.16", "Content per FR-TXT-020", "3"],
    ["FR-SUP-001", "The software shall provide a Frequently Asked Questions page, reachable from the main menu.", "SRS STM.9 and FR-PRT-006; formerly BL-19, restored to its original identifier", "Future development, formerly BL-19. Consolidated per review into a single entry covering both the page and its menu route. Realised by staticData.faqUrl.", "5"],
    ["FR-SUP-004", "The software shall enable the user to initiate a chat session with a support agent.", "SRS STM.10; SRS-BE EX.6, SEC.9; formerly BL-40, restored to its original identifier", "Future development, formerly BL-40. Support by telephone and email remains in the body as FR-SUP-002. The backend SRS requires the chat endpoint and TLS 1.3 with AES-256 at rest for chat content.", "5"],
  ]
},

{
  code: "22",
  title: "Analytics and User Feedback",
  intro: "Requirements for the instrumentation used to observe how the application is used in the field, and for the post-test survey. Both handle data originating from a patient, so the constraints in section 22 apply to them in full.",
  reqs: [
    ["FR-ANL-001", "The software shall record analytics events for the user's progress through the test flow, including step entry and completion, blocking conditions raised, scan attempts and their outcomes, and test completion or invalidation, and shall transmit them to the analytics service.", "Review comment", " Analytics service is Mixpanel; realised by mixpanelProxyEnabled", "3"],
    ["FR-ANL-002", "The software shall not include personal information, health information or test result values in any analytics event.", "Review comment; RA 6.3; SRS ATT.6; SPTA 4.1", "Extends FR-SEC-005 to the analytics path, and applies equally to the audit events required by FR-SEC-013", "3"],
    ["FR-ANL-003", "The software shall associate analytics events with a pseudonymous identifier that cannot be resolved to a patient by the analytics service.", "Review comment", "", "3"],
    ["FR-ANL-005", "Failure of the analytics service, or unavailability of the analytics endpoint, shall not prevent a test from being started, completed, or reported.", "Review comment; derived", " Analytics is not permitted to become a dependency of the clinical flow", "3"],
    ["FR-ANL-004", "The software shall transmit analytics events through the configured proxy endpoint rather than directly to the analytics provider.", "Review comment; formerly BL-28, restored to its original identifier", "Future development, formerly BL-28. Analytics events will reach the provider directly rather than through the proxy until this is implemented; FR-ANL-002 and FR-ANL-003 still bar personal and health information.", "5"],
    ["FR-ANL-006", "The software shall present the configured survey to the user after test completion, opening it in an in-application web view.", "Review comment; SRS-adjacent; formerly BL-29, originally FR-SUR-001", "Future development, formerly BL-29. The post-test survey as a whole moves with FR-ANL-007 and FR-ANL-008.", "5"],
    ["FR-ANL-007", "The software shall permit the user to decline or dismiss the survey, and shall not require its completion in order to reach the test result or the results center.", "Review comment; derived; formerly BL-30, originally FR-SUR-002", "Future development, formerly BL-30. With FR-ANL-006.", "5"],
    ["FR-ANL-008", "The survey web view shall be presented only after the result has been delivered, and shall not be capable of interrupting an active test.", "Derived; formerly BL-31, originally FR-SUR-003", "Future development, formerly BL-31. With FR-ANL-006.", "5"],
    ["FR-ANL-009", "The software shall present the operating system's application-store rating prompt.", "—; formerly BL-32, originally FR-SUR-004", "Future development, formerly BL-32. The application-store rating prompt depends on the chat flow, which is itself deferred.", "5"],
  ]
},

{
  code: "23",
  title: "Security and Data Protection",
  intro: "Requirements protecting personal and health information held on the device or in transit. Most originate in the Security and Privacy Threat Analysis, which is the authority for the threat model; the requirements below are the application obligations that follow from it. FR-SEC-008 to FR-SEC-013 were added from that analysis and had no counterpart in the earlier sources.",
  reqs: [
    ["FR-SEC-001", "The software shall encrypt all sensitive data stored on the device, and shall store only the data required to complete the test and deliver the result.", "SRS ATT.3; SPTA 4.1", "Minimisation obligation added from the threat analysis; retention is bounded by FR-SEC-006", "3"],
    ["FR-SEC-002", "The software shall be published with code obfuscation enabled on the Android platform.", "SRS ATT.4; SPTA 4.11", "Applicable to Android only; iOS has no obfuscation. Agrees with SPTA 4.11. Settled at review; see decision log Q-14", "3"],
    ["FR-SEC-003", "The software shall be published with all debugging functionality and development tools disabled, so that a debugger cannot be attached to a release build.", "SRS ATT.5; SPTA 4.13", "", "3"],
    ["FR-SEC-004", "If an error message occurs, the software shall ensure that no personal information or sensitive details are disclosed to the user.", "SRS ATT.6", "Content per FR-TXT-020. Technical detail is separately constrained by FR-SEC-010", "3"],
    ["FR-SEC-005", "The software shall not write personal or health information to application logs or crash reports.", "Derived; see SPTA", "See also FR-ANL-002", "3"],
    ["FR-SEC-006", "The software shall retain test data on the device only for as long as required to complete transmission, and shall delete it upon backend acknowledgement.", "SRS TSM.27; FR-COM-007", "", "3"],
    ["FR-SEC-007", "The software shall prevent the user from taking a screenshot of any screen containing personal, health or result information, and shall obscure such content when the application is backgrounded or when the operating system captures a preview of it, so that it is not exposed in the application switcher.", "SRS ATT.2; SPTA 4.14", "Screenshot prevention added from the threat analysis. This is the sole control for SPTA 4.14, gross score 12", "3"],
    ["FR-SEC-008", "The software shall not persist any authentication credential, password or long-lived secret on the device. Authentication shall be performed server-side, and a retained session token shall not by itself grant access after sign-out or after the session has expired.", "SPTA 1.5", "New from the threat analysis. SPTA 1.5 scores 16 gross; the stated control is server-side authentication with persistent authentication removed", "3"],
    ["FR-SEC-009", "The software shall store cryptographic keys and session tokens only in the platform-provided secure storage, being the iOS Keychain or the Android Keystore, and shall not write them to application files, shared preferences or any location readable by another application.", "SPTA 4.7", "New from the threat analysis", "3"],
    ["FR-SEC-010", "Error messages presented to the user shall be generic, and shall not disclose internal technical information including stack traces, class or method names, file paths, backend endpoints, component versions or database detail.", "SPTA 1.3", "New from the threat analysis. Distinct from FR-SEC-004, which concerns personal information", "3"],
    ["FR-SEC-011", "The software shall validate and sanitise all user-supplied input before using it, storing it or transmitting it to the backend, accepting only values conforming to the expected type, length and character set for that field.", "SPTA 2.1", "New from the threat analysis. The field-specific rules in FR-AUT-002, FR-AUT-008 and FR-ACC-004 are instances of this requirement, not a substitute for it", "3"],
    ["FR-SEC-012", "Release artefacts for both platforms, being the iOS IPA and the Android APK or AAB, shall be encrypted.", "SPTA 4.11", "New from the threat analysis. Process requirement, verified at release", "3"],
    ["FR-SEC-013", "The software shall report security-relevant events to the backend for audit logging, including authentication attempts and their outcome, PIN entry failures, device-integrity check failures, and any condition that caused a test to be blocked from starting. These events shall carry no personal or health information.", "SPTA 3.1, 3.2", "New from the threat analysis. This is an audit channel distinct from the analytics events required by section 21; FR-ANL-002 applies to both", "4"],
    ["FR-SEC-014", "The software shall not transmit personal or health information from any build in which the transport controls of FR-COM-001 and FR-COM-002 are not fully implemented. Such a build shall be used only with data that did not come from a patient.", "Review decision CR-21; SPTA 2.11, 4.12", "Added at review. Test data upload is at milestone 1 while TLS enforcement and certificate pinning are at milestone 3, so this states the constraint that keeps patient data out of the milestone-1 build", "1"],
  ]
},

{
  code: "24",
  title: "Application Configuration",
  intro: "The application's behaviour is governed at run time by a configuration set retrieved from the backend, resolved per application and per partner. Values that implement a timing, image-validation or assay control are fixed in the application and are not configurable, as stated in the relevant sections. Appendix H registers every configuration and states which requirement it realises.",
  reqs: [
    ["FR-CFG-001", "The software shall retrieve its configuration set from the backend before a test may be started. The set comprises every server-supplied value that governs the behaviour of the application, including those resolved for the application and for the partner associated with the authenticated user. Where retrieval has not yet completed, the software shall indicate that it is not yet ready, and shall not present the condition as a failure.", "Config register", "Broadened at review: the partner-specific values are part of the set rather than the whole of it", "2"],
    ["FR-CFG-002", "If the configuration set cannot be retrieved, or fails validation against the defined schema, the software shall prevent a test from being started and shall not substitute a configuration set embedded in the application build. Where a retrieved and valid set does not supply an individual value, the software shall apply the default defined in the application for that value.", "Config register; derived from RA 4.18, 4.22", "", "2"],
    ["FR-CFG-003", "The software shall record, in the test record transmitted to the backend, the identity and version of the configuration set that was in force for that test.", "Config register; supports RA 4.22; formerly BL-33, restored to its original identifier", "Brought into scope at Guy's direction, formerly BL-33. A completed test carries the configuration it ran under, so a test's configuration can be reconstructed after the fact. It depends on the configuration set that FR-CFG-001 requires, which moved to milestone 2 at the SPEC-04 review; this stays at 3 because recording the set with the test record is a submission obligation rather than something the demonstration or the usability rehearsal needs. Closes Q-32.", "3"],
    ["FR-CFG-004", "Demonstration and mock result behaviour shall be enforced server-side. The backend shall not return a demonstration or mock result for a partner that is not designated as a demonstration partner, irrespective of any value supplied by the application.", "Config register; RA 4.21; formerly BL-34, restored to its original identifier", "Brought into scope for the demonstration at Guy's direction, formerly BL-34. The clause requiring a demonstration result to be labelled was removed at Rev 1.19 per Q-100, because FR-RES-006 already carries that obligation, leaving this a backend rule alone. Server-side enforcement matters because demonstration mode is a state the backend returns with the configuration, so nothing held on the device can be relied on to keep a demonstration result away from a patient. Settles the doubt recorded against Q-31.", "2"],
    ["FR-CFG-006", "Where the configuration places the application in a blocked state, the software shall prevent a test from being started, shall inform the user of the reason, and shall provide support contact information.", "Config register; formerly BL-35, restored to its original identifier", "Brought into scope for the submission at Guy's direction, formerly BL-35. The configured blocked state is a response the product already returns and has screens for; SPEC-01 proposed promoting it. The blocking, notifying and configured-off distinction applies: this one blocks.", "3"],
    ["FR-CFG-008", "The software shall support the integration of components required for the A/B testing interface.", "SRS EX.2; formerly BL-07", "Future development, formerly BL-07. The abTestingEnabled configuration is out of scope; reinstate with this item.", "5"],
  ]
},

{
  code: "25",
  title: "Software Lifecycle and Verification",
  intro: "Requirements arising from risk controls that are implemented through the software development and maintenance process rather than through application behaviour. Development standards, including unit testing, are distinct from release testing and are specified in the Software Development Plan; the requirements below are those the Risk Analysis relies upon.",
  reqs: [
    ["FR-LCM-002", "Off-the-shelf software components shall be evaluated before integration to confirm their suitability, compatibility, and impact on device safety and performance, and shall be obtained only from official sources.", "RA 4.20; SPTA 2.6, 8.1", "Process", "3"],
    ["FR-LCM-003", "Off-the-shelf software components and their updates shall be validated within the complete device software system before release.", "RA 4.20", "Process", "3"],
    ["FR-LCM-004", "The versions and configurations of off-the-shelf software components shall be controlled and recorded, with a continuous inventory maintained by a dependency scanning tool.", "RA 4.20; SPTA 2.6, 2.7, 8.1", "Process. SPTA 8.1 requires scanning weekly and on every update to an off-the-shelf component", "3"],
    ["FR-LCM-005", "Updates, patches, known anomalies, security vulnerabilities and supplier notifications associated with off-the-shelf software components shall be monitored throughout the software lifecycle, and identified changes shall be assessed through the established change-control and risk-management processes.", "RA 4.20; SPTA 2.7, 8.1", "Process. SPTA 2.7 additionally requires subscription to vulnerability bulletins including the CISA Known Exploited Vulnerabilities Catalog", "3"],
    ["FR-LCM-006", "Every parameter identified in the system-parameter appendix shall have a defined value, permitted range and documented rationale before design verification, and shall be held under configuration control whether it is fixed in the application or supplied by configuration.", "RA 4.18", "Process", "3"],
    ["FR-LCM-007", "Each timer and timing window shall be separately verified through release testing, including verification under application backgrounding and interruption.", "RA 4.18", "Process", "3"],
    ["FR-LCM-008", "Regression testing of the timing and test-state controls shall be performed for each applicable software release.", "RA 4.18", "Process", "4"],
    ["FR-LCM-009", "Each algorithm version, and each approved combination of mobile and backend algorithm versions, shall undergo software verification and validation before release. Where a full analytical performance study is not repeated, regression testing shall be performed against the validated reference algorithm using predefined datasets and acceptance criteria.", "RA 4.21", "Process", "3"],
    ["FR-LCM-010", "Release verification shall confirm that the approved algorithm versions and configuration were deployed to the production environment.", "RA 4.22", "Process", "3"],
    ["FR-LCM-011", "Retention and recovery of test state following interruption shall be verified through release testing, and application termination and reopening during each stage of the test flow shall be verified.", "RA 4.1, 7.19", "Process", "3"],
    ["FR-LCM-012", "Usability testing shall include representatives of each supported platform and shall evaluate foreseeable interruptions before, during and after result-critical user actions.", "RA 4.1, 4.2, 4.7", "Process", "3"],
    ["FR-LCM-016", "A dedicated integration testing phase shall be conducted with each medical provider before go-live, verifying connectivity, the accurate transmission and mapping of test result data, routing to the correct provider destination, and the handling of unsuccessful transmissions.", "RA 6.1, 6.2, 6.3", "Process; per provider organisation", "4"],
    ["FR-LCM-017", "Release testing shall be performed before each release, comprising integration, system and regression testing, as detailed in the Software Development Plan. Unit testing and other development standards are specified separately in that plan.", "RA 4.21", "Process", "3"],
    ["FR-LCM-018", "A change to any configuration value recorded in the Application Configuration Register as realising a requirement shall be assessed under the established change-control and risk-management processes before it is applied to the production environment.", "Formerly a requirement in the configuration section; formerly BL-15", "Future development, formerly BL-15.", "5"],
  ]
},

];
