// Security and Privacy Threat Analysis coverage.
// Source: Minuteful – Kidney Test Security and Privacy Threat Analysis,
// MNT-KT-US-SPTA-01 Rev 6.0, 14 Nov 2024. 40 threats across 8 STRIDE groups.
// Only threats whose control is realised in the mobile application, or which
// constrain it, generate requirements here.

// [threat, mode / cause, gross E·S=R -> residual, control per the SPTA, requirement]
exports.appThreats = [
  ["1.1", "Session identifiers are managed improperly", "3·3=9 → 6",
   "Strong session identifiers are implemented", "FR-COM-001"],
  ["1.3", "Error handling reveals internal technical information", "3·2=6 → 4",
   "Generic error messages are implemented", "FR-SEC-010 (new)"],
  ["1.4", "Unauthorized access to the personal information zone of the App", "4·4=16 → 8",
   "Authentication and authorization are in place in the personal information zone", "FR-ACC-001, FR-ACC-002, FR-AUT-013"],
  ["1.5", "Credentials are stored locally", "4·4=16 → 8",
   "Server-side authentication is implemented; persistent authentication is removed", "FR-SEC-008 (new)"],
  ["1.7", "No timeout session configured for the results center", "3·3=9 → 6",
   "After 15 minutes of inactivity the user is returned to the home screen and must resubmit their date of birth; the results center is protected by a PIN; after 24 hours access is blocked if the results have not been viewed", "FR-ACC-006, FR-ACC-009 (new)"],
  ["2.1", "User-supplied data is not validated, filtered or sanitized", "4·4=16 → 4",
   "Input validation is implemented", "FR-SEC-011 (new), FR-AUT-002, FR-AUT-008, FR-ACC-004"],
  ["2.4", "Modification of mobile clients' resources is allowed", "2·4=8 → 4",
   "Input validation on the backend server is implemented as a compensating control", "FR-COM-005"],
  ["2.5", "Malicious application takes control of the mobile device", "2·4=8 → 8",
   "A software mechanism limits the minimum operating-system version supported, so that versions no longer receiving security updates cannot be used to take the test", "FR-RDY-003"],
  ["2.6", "Vulnerable software or libraries are in use", "4·4=16 → 8",
   "Official sources only; unpatched dependencies removed; continuous dependency inventory", "FR-LCM-002, FR-LCM-004, FR-LCM-005"],
  ["2.7", "Nested dependencies present vulnerabilities", "4·4=16 → 8",
   "As 2.6, with subscription to vulnerability bulletins including the CISA Known Exploited Vulnerabilities Catalog", "FR-LCM-005"],
  ["2.11", "Sensitive data is transmitted using insecure methods", "5·4=20 → 8",
   "Data in transit is carried only over secured protocols, TLS 1.2 or above", "FR-COM-001"],
  ["3.1", "Auditable events are not logged or not retained", "5·3=15 → 6",
   "All events are logged with sufficient context; critical transactions logged append-only", "FR-SEC-013 (new)"],
  ["4.1", "Data is stored in plain text on the mobile device", "4·3=12 → 6",
   "Sensitive data stored on the device is minimised; encryption at rest is implemented", "FR-SEC-001, FR-SEC-006"],
  ["4.4", "Data is passed to the backend in plain text", "4·3=12 → 3",
   "Advanced TLS protocols, strong cipher suites and SSL chain verification", "FR-COM-001, FR-COM-002"],
  ["4.5", "Old transport-layer security algorithms are vulnerable", "3·3=9 → 6",
   "TLS versions older than 1.2 are disabled", "FR-COM-001"],
  ["4.7", "Keys are stored in an attacker-readable directory on the mobile device", "3·4=12 → 4",
   "Secured storage is used", "FR-SEC-009 (new)"],
  ["4.11", "Mobile applications are susceptible to source-code analysis", "2·4=8 → 6",
   "Code obfuscation on Android; jailbreak detection; release artefacts encrypted", "FR-SEC-002, FR-SEC-012 (new), FR-RDY-001"],
  ["4.12", "The application has not pinned the certificate of a static remote service", "4·4=16 → 4",
   "Certificate pinning is enforced", "FR-COM-002"],
  ["4.13", "Debugging functionality is enabled", "4·4=16 → 4",
   "Debugging functionality is disabled", "FR-SEC-003"],
  ["4.14", "Data is exposed via screen capture or the app switcher", "4·3=12 → 6",
   "The software prevents the user taking screenshots, and blurs the current screen when the app switcher is invoked", "FR-SEC-007"],
  ["5.2", "Third-party services are unavailable", "4·4=16 → 8",
   "Business continuity and disaster recovery; customer support can offer workarounds", "FR-RDY-006, FR-COM-006, FR-SUP-002"],
  ["5.3", "Cloud availability", "3·3=9 → 6",
   "The User Manual instructs the user how to act during a cloud availability issue; BCP and DR processes", "FR-RDY-006, FR-CFG-006"],
  ["6.1", "Poor authorization scheme", "4·4=16 → 4",
   "Incoming request identifiers are verified on the backend server", "FR-AUT-013, FR-COM-010 (new)"],
  ["8.1", "Third-party off-the-shelf software", "5·3=15 → 6",
   "Weekly dependency scanning and advisory alerts, and on every OTS update", "FR-LCM-002, FR-LCM-004, FR-LCM-005"],
];

// Threats whose controls sit entirely outside the application.
// [group, threats, where the control lives]
exports.outsideApp = [
  ["Cloud access control and identity",
   "1.2, 1.6, 6.2, 7.1, 7.3, 7.5",
   "Google Cloud Platform IAM, zero-trust network, two-factor authentication for administrators, segregation of duties, CORS minimisation and WAF. No application behaviour follows."],
  ["Partner and third-party integration",
   "1.8, 4.16, 5.4",
   "Public and private key authentication with partner servers, firewall rules restricted to verified addresses, partner security assessment and vendor management. Constrains the provider integration in section 20, which is specified as backend."],
  ["Backend input handling and hardening",
   "2.2, 2.3, 2.8, 2.9, 2.10, 4.2, 4.6, 4.8, 4.9, 4.10, 4.15",
   "Interpreter escaping, secure coding patterns, peer review, vulnerability scanning, CSPM, patch management, encryption at rest with AES-256, key management via Cloud Secret Manager and repeatable hardening. Belongs to the backend requirements specification."],
  ["Logging infrastructure",
   "3.2, 3.3",
   "Central log storage and monitoring. The application's obligation is to emit the events, which is FR-SEC-013."],
  ["Denial of service",
   "5.1",
   "Web application firewall. No application behaviour follows."],
  ["Deployment",
   "7.2",
   "Validated deployment scripts, signed cloud artefacts and verification and validation in a test environment before deployment. The application analogue is store distribution, FR-PLT-001, and artefact encryption, FR-SEC-012."],
  ["User responsibility",
   "2.5 (partial), 4.3, 4.11 (partial)",
   "Terms and Conditions and the User Manual require the user to keep their mobile device secure. Not an application requirement."],
];
